translate.AddLanguage("zh-CN", "Chinese Simplified")

-- Various gamemode stuff
LANGUAGE.capture_progress                                   = "已占领 %s - %s / %s "
LANGUAGE.ammo_regeneration                                  =  "子弹在 %s 后重新填装"
LANGUAGE.infliction_rate                                    = "感染率: %d%% "
LANGUAGE.infliction_reached                                 = " %d%% 的人类已经死亡!"
LANGUAGE.infliction_reached_classic                         = "丧尸数量已达到 %d%% !"
LANGUAGE.infliction_reached_class_unlocked                  =  "丧尸数量已达到 %d%% ! %s 种丧尸已解锁"
LANGUAGE.survive                                            = "从丧尸的攻势中生存下来!"
LANGUAGE.survive_wave                                       = "/////丧尸突击进行中/////"
LANGUAGE.survive_wave_sub                                   = "在时间结束前生存下来!"
LANGUAGE.disconnect_killed                                  = " %s 的掉线使 %s 增加了一个人头数."
LANGUAGE.nail_removed_by                                    = " %s 移除了 %s 的一根钉子"
LANGUAGE.deployable_placed_by                               = " %s [%s] 部署 %s 在位置( %s )."
LANGUAGE.late_buyer_warning                                 = "你的Late Buyer技能被激活, 所以你不能在前半场游戏结束之前购买任何物品."
LANGUAGE.round_half_over_arsenal_prices_updated             = "波数已过半,商店内的物品价格已更改"
LANGUAGE.need_to_be_near_arsenal_crate                      = "你需要靠近军械库或者水晶来购买物品"
LANGUAGE.need_to_be_near_remantler                          = "你需要靠近重组机"
LANGUAGE.need_to_be_near_remantler_or_sigil                 = "你需要靠近重组机或者水晶"
LANGUAGE.need_to_be_near_alchemy_table                      = "你需要靠近一个炼金台!"
LANGUAGE.need_to_be_near_sigil                              = "你需要靠近水晶"
LANGUAGE.need_to_be_near_uncorrupted_sigil                  = "你不能在腐化水晶购买物品"
LANGUAGE.target_need_to_be_near_shop                        = "接受者需要靠近一个商店!"
LANGUAGE.too_early_for_honed                                = "你还不能升级这把武器到磨砺等级直到第一波后的90秒"
LANGUAGE.too_early_for_perfected                            = "你还不能升级这把武器到完美等级直到第一波后的3分钟"
LANGUAGE.cant_party_buy_item                                = "你无法大量购买此物品"
LANGUAGE.cant_purchase_right_now                            = "你还无法购买此物品."
LANGUAGE.purchase_is_on_cooldown_for_x_seconds              = "购买冷却还需 %d 秒!"
LANGUAGE.cant_purchase_this_type                            = "你无法购买此类型物品."
LANGUAGE.dont_have_enough_points                            = "你没有足够的点数."
LANGUAGE.dont_have_enough_dark_essence                      = "你没有足够的灵魂精华."
LANGUAGE.dont_have_enough_bounty_tokens                     = "你没有足够的赏金代币."
LANGUAGE.upgrade_can_only_be_purchased_once_per_life        = "每条生命只能购买一次这个升级."
LANGUAGE.upgrade_can_only_be_purchased_on_pointsave         = "这个升级只能在pointsave服务器购买"
LANGUAGE.upgrade_can_only_be_purchased_on_main              = "这个升级只能在main服务器购买."
LANGUAGE.upgrade_is_on_cooldown_for_x_seconds               = "这个升级冷却还有 %d 秒!"
LANGUAGE.upgrade_unlocks_wave_x                             = "这个升级会在 %d 波解锁!"
LANGUAGE.upgrade_currently_has_no_stocks                    = "这个升级目前没有存货!"
LANGUAGE.upgrade_cannot_be_purchased_during_intermission    = "这个升级无法在波数间隔时购买!"
LANGUAGE.upgrade_cannot_be_purchased_whilst_boss            = "这个升级无法在成为boss时购买!"
LANGUAGE.upgrade_cannot_be_purchased_whilst_one_active      = "这个群体增益无法在已有群体增益时购买."
LANGUAGE.upgrade_cannot_be_purchased_team_limit_for_x       = "你的队伍有太多 %ss "
LANGUAGE.upgrade_cannot_currently_be_purchased              = "这个升级目前无法被购买!"
LANGUAGE.upgrade_cannot_selected_weapon_x                   = "无法升级 %s "
LANGUAGE.need_to_have_enough_scrap                          = "你没有足够的零件."
LANGUAGE.cannot_dismantle                                   = "你不能分解这个道具."
LANGUAGE.cannot_upgrade_trinket                             = "你不能升级这个饰品."
LANGUAGE.cannot_drop                                        = "你不能丢弃这个道具."
LANGUAGE.cannot_give                                        = "你不能给出这个物品."
LANGUAGE.prepare_yourself                                   = "做好准备..."
LANGUAGE.purchased_x_for_y_points                           = "购买 %s ,用了 %d 的点数 !"
LANGUAGE.purchased_x_for_y_dark_essence                     = "购买 %s ,用了 %d 的灵魂精华!"
LANGUAGE.purchased_x_for_y_bounty_tokens                    = "购买 %s ,用了 %d 的赏金代币 !"
LANGUAGE.purchased_x_for_y_bounty_token                     = "购买 %s ,用了 %d 的赏金代币 !"
LANGUAGE.purchased_x_missing_scrap_for_y_points             = "购买 %s ,缺少的零件用了 %d 的点数."
LANGUAGE.received_x_from_y                                  = "获得了 %s 赠予者是: %s! 太壕了!"
LANGUAGE.purchased_for_x_denied                             = "%s 拒绝了你的礼物!"
LANGUAGE.purchase_for_target_on_cooldown                    = "赠礼功能还有 %d 秒冷却时间!"
LANGUAGE.created_x_for_y_scrap                              = "制作 %s ,用了 %d 的零件!"
LANGUAGE.give_time_before_suicide                           = "在自杀前请给其他玩家复活的时间!"
LANGUAGE.no_spare_ammo_to_give                              = "没有多余子弹可以给予其他玩家!"
LANGUAGE.no_person_in_range                                 = "距离内无玩家!"
LANGUAGE.that_life                                          = "这条命内..."
LANGUAGE.x_damage_to_barricades                             = "对防线造成了 %d 伤害"
LANGUAGE.x_damage_to_humans                                 = "对人类造成了 %d 伤害"
LANGUAGE.x_brains_eaten                                     = "击杀了 %d 名人类"

LANGUAGE.spawn_options                                      = "重生选择"
LANGUAGE.press_jump_to_free_roam                            = "[JUMP] 进入自由视角"
LANGUAGE.press_lmb_to_spawn                                 = "[LMB] 重生至附近人类"
LANGUAGE.press_reload_to_spawn_far                          = "[RELOAD] 重生到最靠近你视角的丧尸重生点"
LANGUAGE.press_alt_nest_menu                                = "[ALT] 选择菜单"
--LANGUAGE.press_rmb_to_spawn_close                         = "按右键重生到最靠近人类的重生点"
LANGUAGE.press_rmb_to_spawn_nearest_gas                     = "[RMB] 重生到最近的重生点"

LANGUAGE.observing_x                                        = "正在观察 %s (%d)"
LANGUAGE.observing_x_simple                                 = "正在观察 %s "
LANGUAGE.waiting_for_next_wave                              = "正在等待下一波开始..."
LANGUAGE.impossible                                         = "不可能"
LANGUAGE.trying_to_put_nails_in_glass                       = "是什么让你觉得把钉子钉在玻璃上是个好主意?"
LANGUAGE.boss_class_select                                  = "下次你被选为Boss时你将重生为 %s "
LANGUAGE.demi_class_select                                  = "下次你被选为次级Boss时你将重生为 %s "
LANGUAGE.person_has_weapon                                  = "他已经有这把武器了"
LANGUAGE.person_not_on_friends                              = "你已设置只能将物品给予你的好友"
LANGUAGE.cant_do_that_in_classic_mode                       = "你不能在经典模式下那么做"
LANGUAGE.cant_use_x_in_classic_mode                         = "你不能在经典模式下使用 %s "
LANGUAGE.cant_use_x_in_objective_mode                       = "你不能在OBJ地图中使用 %s "
LANGUAGE.cant_use_x_in_zombie_escape                        = "你不能在Zombie Escape地图中使用 %s "
LANGUAGE.no_class_switch_in_this_mode                       = "目前这个模式不允许你切换丧尸种类"
LANGUAGE.press_sprint_to_get_up                             = "按下 冲刺键 爬起"
LANGUAGE.zombie_escape                                      = "丧尸逃生!"
LANGUAGE.nothing_for_this_ammo                              = "你没有任何东西可使用这种子弹"
LANGUAGE.you_decide_to_leave_some                           = "留点物品给你的队友吧"
LANGUAGE.you_cant_purchase_now                              = "你目前不能购买此物品"
LANGUAGE.no_ammo_here                                       = "目前没有弹药"
LANGUAGE.no_food_here                                       = "目前没有食物"
LANGUAGE.you_redeemed                                       = "你已复活!"
LANGUAGE.x_redeemed                                         = " %s 已复活"
LANGUAGE.kill_the_last_human                                = "杀死最后一名人类!"
LANGUAGE.you_are_the_last_human                             = "你是最后一个人类!"
LANGUAGE.x_zombies_out_to_get_you                           = " %d 个丧尸正在杀你来的路上"
LANGUAGE.you_have_died                                      = "你死了"
LANGUAGE.you_were_killed_by_x                               = "你被 %s 杀死"
LANGUAGE.you_were_kicked_by_x                               = "你被 %s 踢到了小腿"
LANGUAGE.arsenal_upgraded                                   = "军械库已更新"
LANGUAGE.auto_reloaded                                      = "你的 %s 已自动装填完毕"
LANGUAGE.final_wave                                         = "最终波已开始!"
LANGUAGE.final_wave_sub                                     = "所有丧尸均已解锁且已无法重生!"
LANGUAGE.wave_x_has_begun                                   = "第 %d 波已开始"
LANGUAGE.point_lost                                         = "已丢失 %s !"
LANGUAGE.point_won                                          = " %s 已被占领!"
LANGUAGE.point_spawn                                        = " %s 已降临!"
LANGUAGE.x_unlocked                                         = " %d 已解锁"
LANGUAGE.wave_x_is_over                                     = "第 %d 波已结束"
LANGUAGE.wave_x_is_over_sub                                 = "丧尸已暂时停止复活"
LANGUAGE.points_for_surviving                               = "通过生存 你得到了 %d 点数"
LANGUAGE.scrap_for_surviving                                = "通过生存 你得到了 %d 零件"
LANGUAGE.you_are_x                                          = "你是 %s !"
LANGUAGE.x_has_risen_as_y                                   = " %s 已成为 %s !!"
LANGUAGE.x_rose_as_y                                        = " %s 已成为 %s !!"
LANGUAGE.x_demis_risen                                      = " %d 名次级boss已出现!"
LANGUAGE.x_has_risen                                        = "出现了一名boss丧尸!"
LANGUAGE.x_has_been_slain_as_y                              = " %s 作为 %s 已被击杀!"
LANGUAGE.cant_use_worth_anymore                             = "你不能再使用开局菜单了!"
LANGUAGE.class_not_unlocked_will_be_unlocked_x              = "这个种类尚未解锁.它将在第 %d 波开始时解锁"
LANGUAGE.you_are_already_a_x                                = "你已经是 %s 了!"
LANGUAGE.you_will_spawn_as_a_x                              = "你将重生为 %s "
LANGUAGE.you_are_now_a_x                                    = "你现在是 %s 了"
LANGUAGE.crafting_successful                                = "成功制作!"
LANGUAGE.x_crafted_y                                        = " %s 制作了 %s "
LANGUAGE.escape_from_the_zombies                            = "从尸群中逃出生天!"
LANGUAGE.too_close_to_another_nail                          = "太靠近另一个钉子"
LANGUAGE.object_too_damaged_to_be_used                      = "这个物件已经过于损坏并且无法再次被使用"
LANGUAGE.cant_remove_nails_of_superior_player               = "对方玩家转生等级比你高,别想着把他钉子拔了"
LANGUAGE.x_turned_on_noclip                                 = " %s 开启了无碰撞飞行"
LANGUAGE.x_turned_off_noclip                                = " %s 关闭了无碰撞飞行"
LANGUAGE.unlocked_on_wave_x                                 = "会在 %d 波解锁"
LANGUAGE.brains_eaten_x                                     = "击杀数：%s "
LANGUAGE.points_x                                           = "点数：%s "
LANGUAGE.points_x_score_x                                   = "点数：%s  分数：%s "
LANGUAGE.points_x_upgrade_x                                 = "点数：%s  升级：%s "
LANGUAGE.points_x_profit_x                                  = "点数：%s  已赚：%s "
LANGUAGE.points_x_score_x_profit_x                          = "点数：%s  分数：%s  已赚：%s"
LANGUAGE.next_wave_in_x                                     = "下一波会在 %s 内到来"
LANGUAGE.wave_ends_in_x                                     = "波数在 %s 内结束"
LANGUAGE.wave_x_of_y                                        = "波数 %d 之 %d"
LANGUAGE.wave_x                                             = "波数 %d "
LANGUAGE.round_x_of_y                                       = "回合 %d 之 %d "
LANGUAGE.zombie_invasion_in_x                               = "丧尸侵略时间还剩 %s "
LANGUAGE.intermission                                       = "波数间隔"
LANGUAGE.press_f2_for_the_points_shop                       = "按F2打开点数商店"
LANGUAGE.breath                                             = "氧气"
LANGUAGE.zombie_volunteers                                  = "丧尸自愿者"
LANGUAGE.x_will_be_y_soon                                   = " %s 即将成为 %s "
LANGUAGE.you_will_be_x_soon                                 = "你即将成为 %s ! 按F3选择Boss!"
LANGUAGE.boss_will_be_selected_soon                         = "一名丧尸即将在%d秒后被选为Boss"
LANGUAGE.x_discount_for_buying_between_waves                = "在波数间隔时,购买物品将会有 %d%% 折扣"
LANGUAGE.number_of_initial_zombies_this_game                = "这场游戏的初始丧尸数量为 (%d%%): %d "
LANGUAGE.humans_closest_to_spawns_are_zombies               = "最靠近丧尸重生点的人类将被选为丧尸"
LANGUAGE.waiting_for_players                                = "正在等待玩家..."
LANGUAGE.requires_x_people                                  = "需要 %d 名玩家"
LANGUAGE.packing_others_object                              = "正在拿起其他玩家的 %s "
LANGUAGE.packing                                            = "正在拿起 %s "
LANGUAGE.ze_humans_are_frozen_until_x                       = "在回合开始前,人类将被冷冻至 %d 秒"
LANGUAGE.loading                                            = "载入中..."
LANGUAGE.next_round_in_x                                    = "下一回合在：%s "
LANGUAGE.warning                                            = "警告!"
LANGUAGE.ready                                              = "准备"
LANGUAGE.ok_and_no_reminder                                 = "好了,不要再跳出这个信息了"
LANGUAGE.classic_mode_warning                               = " -- 本服务器运行的是‘经典模式’僵尸生存\n经典模式会极大地改变游戏玩法,被改变的内容有：\n* 无法选择僵尸种类.所有人都只能使用经典僵尸\n*没有例如钉子、炮台之类的防守道具\n* 波数更多同时每波时间更快\n\n这个模式是v1版本的僵尸生存!\n\n-- 运行经典模式的服务器会在屏幕左下角显示‘经典模式’"
LANGUAGE.classic_mode                                       = "经典模式"
LANGUAGE.resist_x                                           = "抗性：%d%% "
LANGUAGE.right_click_to_hammer_nail                         = "使用锤子右键钉钉子"
LANGUAGE.nails_x                                            = "钉子：%d "
LANGUAGE.resupply_box                                       = "补给箱"
LANGUAGE.purchase_now                                       = "现在购买!"
LANGUAGE.integrity_x                                        = "完整度: %d%% "
LANGUAGE.empty                                              = "空"
LANGUAGE.manual_control                                     = "手动控制"
LANGUAGE.arsenal_crate                                      = "军械库"
LANGUAGE.not_enough_room_for_a_nest                         = "没有足够空间放下巢穴!"
LANGUAGE.too_close_to_another_nest                          = "太靠近其他巢穴"
LANGUAGE.nest_created                                       = "巢穴已开始建造!完成建造以让丧尸在此处复活"
LANGUAGE.nest_built_by_x                                    = "一个巢穴被 %s 建造 已成为当前丧尸复活点"
LANGUAGE.nest_destroyed                                     = "一个巢穴已被摧毁"
LANGUAGE.nest_destroyed_by_zombie                           = "一个巢穴已被 %s 摧毁"
LANGUAGE.wait_x_seconds_before_making_a_new_nest            = "你必须等待 %d 秒后才能建造新的巢穴"
LANGUAGE.too_close_to_a_human                               = "太靠近人类!"
LANGUAGE.too_close_to_a_spawn                               = "太靠近一个丧尸出生点"
LANGUAGE.too_close_to_uncorrupt                             =  "太靠近一个未被腐化的水晶!"
LANGUAGE.x_has_built_this_nest_and_is_still_around          = " %s 建造了这个巢穴且他还在附近,所以你无法摧毁这个巢穴"
LANGUAGE.no_other_nests                                     = "你无法在只剩下一个巢穴的情况下摧毁巢穴"
LANGUAGE.there_are_too_many_nests                           = "此处巢穴过多 你无法继续建造更多巢穴"
LANGUAGE.you_have_made_too_many_nests                       = "你已达到建造上限,拆除一个巢穴后再尝试建造"
LANGUAGE.no_free_channel                                    = "你已经放置太多的信标"
LANGUAGE.tier_x_items_unlock_at_wave_y                      = "阶级 %d 的道具将在第 %d 波解锁"
LANGUAGE.tier_x_items                                       = "阶级 %d 物品"
LANGUAGE.humans_furthest_from_sigils_are_zombies            = "离水晶最远的人类将被选为起始丧尸"
LANGUAGE.out_of_stock                                       = "这个物品已售空!"
LANGUAGE.acquired_x_y                                       = "获得了 %d 个 %s"
LANGUAGE.obtained_x_y_ammo                                  = "获得了 %d 发 %s 弹药"
LANGUAGE.gave_x_y_ammo_to_z                                 = "给予 %d 发 %s 弹药给 %s "
LANGUAGE.obtained_x_y_ammo_from_z                           = "获得了 %d 发 %s 的弹药来自 %s "
LANGUAGE.healed_x_by_y                                      = "%s 治疗了你 %d HP"
LANGUAGE.temphealed_x_by_y                                  = "%s 给予了你 %d 的临时血量"
LANGUAGE.healed_x_by_y_armor                                = "%s 治疗了你 %d 的血甲"
LANGUAGE.healed_x_for_y                                     = "治疗了 %s %d HP"
LANGUAGE.temphealed_x_for_y                                 = "给予了 %s %d 的临时血量"
LANGUAGE.buffed_x_with_y_for_z                              = "%s 使用 %s 给予你 %d 秒的buff"
LANGUAGE.buffed_x_with_a_y_for_z                            = "给 %s 用 %s 提供了 %d 秒的buff"
LANGUAGE.removed_your_nail                                  = " %s 移除了你的一根钉子"
LANGUAGE.giving_items_to                                    = "将物品给予 %s "
LANGUAGE.weapon_remantler                                   = "重组机"
LANGUAGE.remantle_success                                   = "武器重组"
LANGUAGE.remantle_success_tr                                = "饰品重组"
LANGUAGE.remantle_used                                      = " %d 个零件已从你的重组机中制作出"
LANGUAGE.remantle_cannot                                    = "你已拥有此武器的这一类型"
LANGUAGE.remantle_branch_disabled                           = "这种武器的分支线路已被禁用"
LANGUAGE.teleporting_to_sigil                               = "正在传送至水晶 %s "
LANGUAGE.teleporting_to_supplycrate                         = "正在传送至军械水晶"
LANGUAGE.teleporting_to_x                                   = "正在传送至 %s "
LANGUAGE.press_shift_to_cancel                              = "按下 SHIFT 以取消"
LANGUAGE.point_at_a_sigil_to_choose_destination             = "鼠标指向目标水晶以决定传送目的地"
LANGUAGE.obtained_a_inv                                     = " %s 以被添加至你的装备栏中"
LANGUAGE.you_already_have_this_trinket                      = "你的装备栏中已拥有这个饰品"
LANGUAGE.you_already_have_this_trait                        = "你已经拥有这个特性"
LANGUAGE.swapped_trinket                                    = "你已切换至一个更高等级的饰品"
LANGUAGE.they_already_have_this_trinket                     = "目标已拥有此饰品"
LANGUAGE.they_already_have_too_many                         = "目标已拥有这些饰品"
LANGUAGE.you_cannot_carry_more_comps                        = "你不能携带更多此类原材料"
LANGUAGE.they_cannot_carry_more_comps                       = "目标不能携带更多此类原材料"
LANGUAGE.obtained_inv_item_from_z                           = "你的装备栏添加了 %s ,是 %s 给的 "
LANGUAGE.deployable_lost                                    = "你失去了 %s "
LANGUAGE.deployable_claimed                                 = "你现在拥有 %s "
LANGUAGE.trinket_consumed                                   = "你的 %s 已被消耗且激活"
LANGUAGE.trinket_used                                       = "你的 %s 已被激活"
LANGUAGE.skill_used                                         = "你的 %s 技能已触发"
LANGUAGE.ran_out_of_ammo                                    = "你的 %s 的弹药已消耗完毕"
LANGUAGE.trinket_recharged                                  = "你的 %s 已冷却完毕且可以再次使用"
LANGUAGE.evolves_in_to_x_on_wave_y                          = "你进化为 %s 在第 %d 波"
LANGUAGE.evolves_in_to_x_in_special                         = "特别情况时你会进化为 %s "
LANGUAGE.you_have_been_awarded_xp_for_cades                 = "从造防线中获得了 %d 经验"
LANGUAGE.you_have_been_awarded_points_for_cades             = "从造防线中获得了 %d 点数"
LANGUAGE.need_to_be_near_transponder                        = "你需要靠近一个素材打印机"
LANGUAGE.cant_buy_props                                     = "你无法购买那个素材"
LANGUAGE.weapon_tier_x_unlocked                             = "阶级 %d 的武器已解锁"
LANGUAGE.past_wave_buy_limit                                = "这个物品已无法购买"
LANGUAGE.receieved_x_dark_essence_for_killing_y             = "收到了 %d 点灵魂精华，因为你击杀了 %s."
LANGUAGE.gunk_jump_message                                    = "按下 JUMP 逃走!!!"

--cooking
LANGUAGE.cooking_success                                    = "食物合成："
LANGUAGE.flask_success                                      = "烧瓶化合:"

--spectator
LANGUAGE.press_lmb_to_cycle_forward                         = "按左键切换到下一位玩家"
LANGUAGE.press_rmb_to_cycle_backward                        = "按右键切换到前一个玩家"
LANGUAGE.press_reload_to_roam                               = "按换弹键进入自由视角"
LANGUAGE.press_walk_to_unspectate                           = "按慢走键解除观察"
LANGUAGE.you_are_now_a_spectator                            = "你现在是观察者"
LANGUAGE.moving_to_spectator_because_gone_x_seconds         = "你被移至观察者因为挂机超过 %d 秒"
LANGUAGE.moving_to_zombie_because_gone_x_seconds            = "你被移至丧尸阵营因为挂机超过 %d 秒"

-- Objective Mode unlocks
LANGUAGE.class_not_unlocked_yet_unlocked_in_x               = "这个丧失种类还未解锁. 它将会在 %s 时解锁"
LANGUAGE.class_is_locked_obj                                = "这个丧尸种类在OBJ地图禁用"
LANGUAGE.zombie_in_x                                        = "波数 %s 的丧尸会在 %s 内解锁"
LANGUAGE.you_will_be_x_in_x                                 = "你将变成 %s 在 %s 的时候!"
LANGUAGE.x_will_be_y_in_z                                   = " %s 将会变成 %s 在 %s 的时候!"

-- High priority kill
LANGUAGE.hpk_failed_to_be_killed                            = "优先击杀玩家没有被杀死! 再接再厉!"
LANGUAGE.hpk_selected_notify                                = " %s 现在是优先击杀玩家,杀死他以获得 %d 经验"
--LANGUAGE.hpk_selected_notify                              = " %s 现在是优先击杀玩家,杀死他以获得 %d 点数"
LANGUAGE.hpk_self_notify                                    = "你已经变成优先击杀玩家, 请勿让丧尸杀死你"
LANGUAGE.attacker_recieved_hpk_bounty                       = "因为你杀了优先击杀玩家所以你获得了 %d 经验"
--LANGUAGE.attacker_recieved_hpk_bounty                     = "因为你杀了优先击杀玩家所以你获得了 %d 点数"
LANGUAGE.hpk_killed_by_zombie                               = " %s 杀死了优先击杀玩家并获得了 %d 经验"
--LANGUAGE.hpk_killed_by_zombie                             = " %s 杀死了优先击杀玩家并获得了 %d 点数"
LANGUAGE.hpk_has_disconnected                               = "优先击杀玩家已离开! 正在选择其他玩家"
LANGUAGE.hpk_has_died                                       = "优先击杀玩家死于意外!正在选择其他玩家"
LANGUAGE.hpk_award                                          = "因为优先击杀玩家已死亡,你获得了 %d 经验!"
--LANGUAGE.hpk_award                                        = "因为优先击杀玩家已死亡, 你获得了 %d 点数"

-- Sigils point objectives
LANGUAGE.sigil                                              = "水晶"
LANGUAGE.sigil_corrupted                                    = "一个水晶已被腐化. 丧尸变得更抗打"
LANGUAGE.sigil_corrupted_last                               = "最后一个水晶已被腐化! 丧尸变得非常抗打!"
LANGUAGE.sigil_corrupted_event                              = "最后一个水晶已被腐化! 终焉将至!"
LANGUAGE.sigil_uncorrupted                                  = "一个水晶被修复, 丧尸被削弱!"
LANGUAGE.sigil_corrupted_x_remain                           = " %d个水晶未被腐化"
LANGUAGE.prop_obj_exit_h                                    = "''快逃!"
LANGUAGE.prop_obj_exit_z                                    = "''阻止他们!"
LANGUAGE.x_sigils_appeared                                  = " %d 个水晶已降临. 人类可以从水晶购买物品或在它们之间传送"
LANGUAGE.has_survived                                       = "已逃离"

-- Skill system messages
LANGUAGE.unspent_skill_points_press_x                       = "你有未使用的技能点数. 按 %q 来解锁新技能."
LANGUAGE.x_requires_a_skill_you_dont_have                   = " %s 需要你先解锁上个技能! "
LANGUAGE.you_ascended_to_level_x                            = "你升到了 %d 级!"
LANGUAGE.you_have_remorted_now_rl_x                         = "你已经转生,你的转生等级为 %d !"
LANGUAGE.you_now_have_x_extra_sp                            = "你现在有 %d 额外点数!"
LANGUAGE.x_has_remorted_to_rl_y                             = " %s 已转生至 %d 级"
LANGUAGE.you_have_reset_all                                 = "所有的技能和技能点数已被重置"

LANGUAGE.unspent_dark_essence_press_x                       = "你有未使用的灵魂精华. 按 %q 打开灵魂市场使用"
-- Supply crate objectives
LANGUAGE.supply_crate                                       = "军械水晶"
LANGUAGE.supplycrate_destroyed                              = "一个军械水晶已被摧毁. 丧尸变得更抗打!"
LANGUAGE.supplycrate_destroyed_last                         = "最后一个军械水晶已被摧毁. 丧尸变得非常抗打!"
LANGUAGE.supplycrate_destroyed_event                        = "最后一个军械水晶已被摧毁.终焉将至!"
LANGUAGE.supplycrate_repaired                               = "一个军械水晶被修复, 丧尸被削弱!"
LANGUAGE.supplycrate_destroyed_x_remain                     = " %d 个军械水晶未被摧毁"
LANGUAGE.x_supplycrates_appeared                            = " %d 个军械水晶已降临. 人类可以从中购买特殊物品"
LANGUAGE.need_to_be_near_supply_crate                       = "你需要靠近军械水晶!"

--Phase orb
LANGUAGE.phase_orb_not_enough_room                          = "空间过小"
LANGUAGE.phase_orb_too_near_sigil                           = "''太靠近水晶了"
LANGUAGE.phase_orb_too_near_supplycrate                     = "''太靠近军械水晶了!"
LANGUAGE.phase_orb_too_near_exitpoint                       = "太靠近逃生通道了!"

-- Message beacon messages
LANGUAGE.message_beacon_1               = "在这里集合"
LANGUAGE.message_beacon_2               = "这里需要防守"
LANGUAGE.message_beacon_3               = "这里需要炮台"
LANGUAGE.message_beacon_4               = "此处需要军械库"
LANGUAGE.message_beacon_5               = "这里需要医师"
LANGUAGE.message_beacon_6               = "这里有补给箱"
LANGUAGE.message_beacon_7               = "放逐水晶在这里"
LANGUAGE.message_beacon_8               = "这里需要防御立场"
LANGUAGE.message_beacon_9               = "这里需要爆炸物"
LANGUAGE.message_beacon_10              = "丧尸从这里来"
LANGUAGE.message_beacon_11              = "不要进去!!"
LANGUAGE.message_beacon_12              = "不要出去"
LANGUAGE.message_beacon_13              = "防守这个区域"
LANGUAGE.message_beacon_14              = "防守这个地点"
LANGUAGE.message_beacon_15              = "医师在这"
LANGUAGE.message_beacon_16              = "用我的商店购买"
LANGUAGE.message_beacon_17              = "在这里建立防线"
LANGUAGE.message_beacon_18              = "不要在此处建防线"
LANGUAGE.message_beacon_19              = "不要让丧尸到达这里"
LANGUAGE.message_beacon_20              = "此处将被破开"
LANGUAGE.message_beacon_21              = "这里很危险!"
LANGUAGE.message_beacon_22              = "小心剧毒!"
LANGUAGE.message_beacon_23              = "丧尸正在破坏此处!"
LANGUAGE.message_beacon_24              = "丧尸来了.在此处建造防线!"
LANGUAGE.message_beacon_25              = "这里为B计划"
LANGUAGE.message_beacon_26              = "此处为钓鱼地点"

-- Class names
LANGUAGE.class_zombie                       = "丧尸"
LANGUAGE.class_zombie_ichor                 = "脓液丧尸"
LANGUAGE.class_poison_zombie                = "剧毒丧尸"
LANGUAGE.class_wild_poison_zombie           = "野生剧毒丧尸"
LANGUAGE.class_alpha_poison_zombie          = "原初剧毒丧尸"
LANGUAGE.class_fast_zombie                  = "快速丧尸"
LANGUAGE.class_violator                     = "撕裂者"
LANGUAGE.class_crimson_render               = "绯红入侵者"
LANGUAGE.class_fast_zombie_slingshot        = "弹射丧尸"
LANGUAGE.class_bloated_zombie               = "臃胖丧尸"
LANGUAGE.class_vile_monster                 = "剧毒怪物"
LANGUAGE.class_classic_zombie               = "经典丧尸"
LANGUAGE.class_super_zombie                 = "超级丧尸"
LANGUAGE.class_fresh_dead                   = "感染者"
LANGUAGE.class_recent_dead                  = "变异体"
LANGUAGE.class_agile_dead                   = "敏捷感染者"
LANGUAGE.class_ghoul                        = "食尸鬼"
LANGUAGE.class_chilled_ghoul                = "寒冷食尸鬼"
LANGUAGE.class_elderghoul                   = "长老食尸鬼"
LANGUAGE.class_venerableghoul               = "古代食尸鬼"
LANGUAGE.class_frostbittenghoul             = "寒冰食尸鬼"
LANGUAGE.class_noxiousghoul                 = "剧毒食尸鬼"
LANGUAGE.class_primeghoul                   = "精英食尸鬼"
LANGUAGE.class_headcrab                     = "猎头蟹"
LANGUAGE.class_broodcrab                    = "幼体猎头蟹"
LANGUAGE.class_eliminatorcrab               = "爆炸猎头蟹"
LANGUAGE.class_fast_headcrab                = "敏捷猎头蟹"
LANGUAGE.class_bloodsucker_headcrab         = "嗜血猎头蟹"
LANGUAGE.class_poison_headcrab              = "剧毒猎头蟹"
LANGUAGE.class_barbed_headcrab              = "刺猬猎头蟹"
LANGUAGE.class_carrion_headcrab             = "腐化猎头蟹"
LANGUAGE.class_the_tickle_monster           = "长手怪"
LANGUAGE.class_nightmare                    = "梦魇"
LANGUAGE.class_fleshfire                    = "焚烧尸"
LANGUAGE.class_darkmare                     = "暗魇"
LANGUAGE.class_ancient_nightmare            = "远古梦魇"
LANGUAGE.class_devourer                     = "吞噬魔"
LANGUAGE.class_abductor                     = "诱拐怪"
LANGUAGE.class_pukepus                      = "剧毒君王"
LANGUAGE.class_bilemire                     = "剧毒魔"
LANGUAGE.class_bonemesh                     = "投骨者"
LANGUAGE.class_tarmesh                      = "投尸者"
LANGUAGE.class_crow                         = "乌鸦"
LANGUAGE.class_wilowisp                     = "闪光精灵"
LANGUAGE.class_coolwisp                     = "寒冰精灵"
LANGUAGE.class_zombie_torso                 = "爬行尸"
LANGUAGE.class_zombie_legs                  = "丧尸腿"
LANGUAGE.class_wraith                       = "恶灵"
LANGUAGE.class_tormented_wraith             = "痛苦恶灵"
LANGUAGE.class_spectre                      = "幽灵"
LANGUAGE.class_fast_zombie_legs             = "奔跑腿"
LANGUAGE.class_fast_zombie_torso            = "奔跑爬行尸"
LANGUAGE.class_fast_zombie_torso_slingshot  = "弹射爬行尸"
LANGUAGE.class_chem_fiend                   = "生化枯骨"
LANGUAGE.class_chem_burster                 = "生化破坏者"
LANGUAGE.class_shade                        = "万磁王"
LANGUAGE.class_frostshade                   = "寒霜万磁王"
LANGUAGE.class_butcher                      = "屠夫"
LANGUAGE.class_gravedigger                  = "掘墓人"
LANGUAGE.class_flesh_creeper                = "筑巢怪"
LANGUAGE.class_flesh_weaver                 = "筑巢魔"
LANGUAGE.class_gore_child                   = "血婴"
LANGUAGE.class_giga_gore_child              = "残暴血婴"
LANGUAGE.class_shadow_gore_child            = "暗影血婴"
LANGUAGE.class_giga_shadow_child            = "暗影残暴血婴"
LANGUAGE.class_asskicker                    = "爆菊大腿"
LANGUAGE.class_shitslapper                  = "大巴掌"
LANGUAGE.class_doomcrab                     = "灭世王蟹"
LANGUAGE.class_red_marrow                   = "红骨"
LANGUAGE.class_cold_marrow                  = "冰骨"
LANGUAGE.class_skeletal_walker              = "枯骨行者"
LANGUAGE.class_skeletal_shambler            = "枯骨"
LANGUAGE.class_skeletal_lurker              = "骨头爬行尸"
LANGUAGE.class_skeleton_warrior             = "枯骨战士"
LANGUAGE.class_cinder_skeleton_warrior      = "余烬枯骨勇士"
LANGUAGE.class_deadeye                      = "死亡之眼"
LANGUAGE.class_skeleton_archer              = "枯骨弓箭手"
LANGUAGE.class_skeleton_executioner         = "枯骨刽子手"
LANGUAGE.class_dread_knight                 = "恐惧骑士"
LANGUAGE.class_dread_shadow                 = "惧影傀儡"
LANGUAGE.class_ice_demon                    = "寒霜魔"
LANGUAGE.class_ice_devil                    = "寒霜恶魔"
LANGUAGE.class_shadow_lurker                = "暗影潜伏者"
LANGUAGE.class_abyss_lurker                 = "深渊潜伏者"
LANGUAGE.class_shadow_walker                = "暗影行者"
LANGUAGE.class_frigid_revenant              = "寒冷亡魂"
LANGUAGE.class_initial_dead                 = "初始感染体"
LANGUAGE.class_lacerator                    = "致残者"
LANGUAGE.class_lacerator_charging           = "冲撞者"
LANGUAGE.class_dread_fallen                 = "暗影堕落者"
LANGUAGE.class_dread_hulk                   = "惧影巨人"
LANGUAGE.class_dread_grunt                  = "惧影狂徒"
LANGUAGE.class_dread_brute                  = "惧影骇兽"
LANGUAGE.class_dread_bloated                = "惧影跛行者"
LANGUAGE.class_dread_reaper                 = "惧灭死神"
LANGUAGE.class_tickle_torment               = "刺挠折磨者"
LANGUAGE.class_chem_jaeger                  = "生化猎手"
LANGUAGE.class_ice_marrow                   = "冻骨"
LANGUAGE.class_tormentor                    = "折磨者"

LANGUAGE.class_chem_charger                 = "生化冲撞者"
LANGUAGE.class_chem_zombie                  = "生化丧尸"
LANGUAGE.class_eradicator                   = "铲除者"
LANGUAGE.class_annihilator                  = "歼灭者"
LANGUAGE.class_brood_zombie                 = "幼体丧尸"
LANGUAGE.class_howler                       = "尖啸魔"
LANGUAGE.class_lich                         = "巫妖"
LANGUAGE.class_extinctioncrab               = "灭绝猎头蟹"
LANGUAGE.class_lesserheresiarch             = "异端幼体"
LANGUAGE.class_lessergloomwalker            = "幽暗行者"
LANGUAGE.class_bloodangel                   = "驭血天使"
LANGUAGE.class_sigil_tyrant                 = "水晶暴君"
LANGUAGE.class_heresiarch                   = "异端体"
LANGUAGE.class_sanity_sentinel              = "晶体哨卫"
LANGUAGE.class_gloomwalker                  = "幽暗漫步者"
LANGUAGE.class_corruptor                    = "腐晶魔"
LANGUAGE.class_sigilite                     = "晶体界守"
LANGUAGE.class_hate                         = "恶魔暴君"
LANGUAGE.class_gunk_zombie                  = "粘液丧尸"
LANGUAGE.class_gunk_fiend                   = "粘液魔鬼"
LANGUAGE.class_tar_monster                  = "粘液怪"
LANGUAGE.class_rune_watcher                 = "符文观察者"
LANGUAGE.class_gunk_zombie_torso            = "粘液爬行尸"
LANGUAGE.class_gunk_zombie_legs             = "粘液腿"
LANGUAGE.class_viper                        = "毒蛇"
LANGUAGE.class_parasite                     = "袭掠寄生体"
LANGUAGE.class_chemjuggernaut               = "化学主宰"
LANGUAGE.class_propmonster                  = "腐败钢兽"
LANGUAGE.class_brood_queen                  = "幼体女皇"
LANGUAGE.class_headcrab_hatchling           = "小型猎头蟹"
LANGUAGE.class_disruptor                    = "破坏者"
LANGUAGE.class_hemorrite                    = "血肉集合体"
LANGUAGE.class_ice_fiend                    = "寒冰魔鬼"
LANGUAGE.class_marrow_tyrant                = "红骨暴君"
LANGUAGE.class_flesh_sentinel               = "血肉哨卫"
LANGUAGE.class_abhorrent_amalgam            = "猩红怒兽"
LANGUAGE.class_bigghoul                     = "巨型食尸鬼"
LANGUAGE.class_tickle_nightmare             = "触手梦魇"
LANGUAGE.class_the_lost                     = "迷途魔"
LANGUAGE.class_spectral_revenant            = "幽灵亡魂"
LANGUAGE.class_fetid_maw                    = "恶臭亡魂"
LANGUAGE.class_gonome                       = "脓包猎头鬼"
LANGUAGE.class_harbinger                    = "先驱猎头鬼"
LANGUAGE.class_breachprowler                = "破界游荡者"
LANGUAGE.class_dreadmammoth                 = "暗影长毛象"
LANGUAGE.class_hulk                         = "巨人"
LANGUAGE.class_cinder_thug                  = "灰烬暴徒"
LANGUAGE.class_cinder_ghoul                 = "燃烧食尸鬼"
LANGUAGE.class_alphacrab                    = "血腥猎头蟹"
LANGUAGE.class_meteoric_eradicator          = "陨石铲除者"
LANGUAGE.class_pigeon                       = "鸽子"
LANGUAGE.class_seagull                      = "海鸥"
LANGUAGE.class_banished_warrior             = "放逐勇士"
LANGUAGE.class_restlesszombie               = "不息丧尸"
LANGUAGE.class_restless_zombie_torso        = "不息丧尸躯干"
LANGUAGE.class_flesh_breaker                = "血肉破坏者"
LANGUAGE.class_behemoth                     = "贝希摩斯"

--Hardmode Classes
LANGUAGE.class_dread_monger                 = "恐惧之源"
LANGUAGE.class_amalgam                      = "奇美拉"
LANGUAGE.class_moroi                        = "吸血鬼"
LANGUAGE.class_elemental                    = "元素"
LANGUAGE.class_frostbite                    = "冻疮噬咬者"
LANGUAGE.class_nuclear_terror               = "辐射恐慌者"
LANGUAGE.class_poison_anomaly               = "剧毒异变者"
LANGUAGE.class_gonarch                      = "格纳库"
LANGUAGE.class_tickledecimator              = "刺挠屠杀者"

-- Class descriptions
LANGUAGE.description_zombie                         = "普通僵尸,拥有较高的身体强度和强大的爪子\n如果没有被爆头就很难被放倒."
LANGUAGE.description_zombie_ichor                   = "脓液僵尸,其锋利的锯齿状爪子被粘液所覆盖.它们所丢出的脓疱会造成bleed和gunk."
LANGUAGE.description_poison_zombie                  = "此僵尸变种不仅身体强度很高而且拥有异常强大的力量.\n它的身体拥有剧毒,如果攻击目标太远甚至会撕扯自己的血肉并丢向他们"
LANGUAGE.description_wild_poison_zombie             = "剧毒僵尸的不规则变种,因此它们更强壮,血也更厚.\n它们投掷的血肉更加致命且范围更广."
LANGUAGE.description_alpha_poison_zombie            = "一个身经百战的野生剧毒僵尸,其上肢拥有出乎意料的物理强度且爪击距离更远.\n拥有剧毒爪击且能投掷血肉."
LANGUAGE.description_fast_zombie                    = "全身几乎没有血肉的僵尸,拥有比其他僵尸更快的速度.\n它们能构成的威胁不大,但是它们的利爪能让自己攀爬到几乎任何地方\n它们能轻易拿下受伤的人类."
LANGUAGE.description_violator                       = "一种快速而坚韧的僵尸,可以跳跃的很远.\n经常可以见到它们扑在外场的人类身上.\n它们非常顽强,即使受到重击也很难被放倒."
LANGUAGE.description_crimson_render                 = "浑身被血覆盖的快速僵尸,拥有碎甲爪击且可以喷出浓血.\n经常可以见到它们扑在外场的人类身上.\n它们非常顽强,即使受到重击也很难被击倒."
LANGUAGE.description_fast_zombie_slingshot          = "一个异常的快速僵尸,会进行强烈的猛冲.\n其猛冲的力量过于强大以至于它的下肢会直接被摧毁,并将自己的上身以极快的速度发射出去.\n其造成的冲击会让人类暂时减速."
LANGUAGE.description_bloated_zombie                 = "它们的身体由有挥发性的剧毒化学物质组成.\n虽然他们的移动速度较慢,但他们可以承受更多的打击."
LANGUAGE.description_vile_monster                   =  "它们的身体由有挥发性的剧毒化学物质组成.并且能呕吐至较远的位置"
LANGUAGE.description_fresh_dead                     =  "这些僵尸最近起死回生.\n它们的身体强度和力量不如已经腐烂的僵尸,但在速度上有所弥补."
LANGUAGE.description_agile_dead                     =  "这些僵尸最近起死回生.\n变异使得它们能以变得极其脆弱的代价进行攀爬"
LANGUAGE.description_super_zombie                   =  "这些僵尸最近才起死回生,但是它们不容小觑.\n它们的身体强度极高,很难被击倒,同时还非常机动."
LANGUAGE.description_ze_zombie                      =  "这些僵尸只在僵尸逃跑中出现."
LANGUAGE.description_ghoul                          =  "这种僵尸的肉体有剧毒.\n它比其他僵尸略微弱一些,但它有易伤攻击来弥补.\n它的爪子可以在短时间内对人类施加debuff,导致人类受到更高的伤害,它可以扔出粘液球,使人类减速."
LANGUAGE.description_chilled_ghoul                  =  "这种僵尸有极寒的肉体.\n它比其他僵尸稍弱,但它有易伤攻击来弥补."
LANGUAGE.description_frigid_revenant                =  "一个拥有冰心的暗黑骷髅.\n从寒冷食尸鬼衍生而来,拥有和暗影行者一样对近战攻击的抗性.\n它的攻击能施加寒冷、致盲并消耗人类体力."
LANGUAGE.description_elderghoul                     =  "一个拥有剧毒身体的陈年食尸鬼,他们会向远处的受害者投掷有毒的碎片.\n他们虚弱的身体会在受到伤害时向攻击者释放毒物."
LANGUAGE.description_venerableghoul                 =  "掌握了腐败艺术的焦黑老食尸鬼.\n他们的投掷物可以施加易伤,爪击会减速人类.\n他们虚弱的身体在受到伤害时,会向攻击者释放毒物."
LANGUAGE.description_noxiousghoul                   =  "一个极度老化的食尸鬼,其身体与高毒性的粘液融合在一起.\n他们的投射物会使不幸的受害者变得缓慢和虚弱,他们的身体会在受到伤害时向攻击者释放毒物."
LANGUAGE.description_frostbittenghoul               =    "受冬之诅咒影响的食尸鬼.\n他们的投掷物会减缓并冻结任何接触到的物体.\n他们的爪击会传递冬之诅咒debuff."
LANGUAGE.description_primeghoul                     =  "所有食尸鬼的至高之神.\n他们的投掷物将完全击溃不幸的受害者,而且他们的身体在受到伤害时将向攻击者释放毒物."
LANGUAGE.description_headcrab                       =  "最初的感染是由猎头蟹引起的.\n没有人知道它们到底从哪来.\n它们的攻击方式是用腹部的尖喙跃击."
LANGUAGE.description_broodcrab                      =  "这种猎头蟹已经进化出更坚硬的皮肤,以应对更强大的猎物.\n对范围伤害的抵抗力增加."
LANGUAGE.description_eliminatorcrab                 =  "对单体目标能造成巨大的额外伤害.死亡时会对人类发射追踪爆炸球."
LANGUAGE.description_fast_headcrab                  =  "雄性猎头蟹的速度相当快,但没有雌性头蟹那么强壮.\n不管是哪种头蟹,它们群起而攻的时候既烦人又致命."
LANGUAGE.description_bloodsucker_headcrab           =  "嗜血猎头蟹是更加强壮的敏捷猎头蟹,咬人时出血量大.\n每成功咬人一次,就会恢复少量的血量."
LANGUAGE.description_poison_headcrab                =  "这种猎头蟹充满了致命的神经毒素.\n咬一口通常就足以杀死一个成年人类.\n它还能吐出效力较弱的毒药.\n吐出的毒液也和脸上被咬同样致命"
LANGUAGE.description_barbed_headcrab                =  "这种猎头蟹长着锋利的毒刺.它能以高速投射出刚毛,对不幸的人类造成出血和中毒."
LANGUAGE.description_carrion_headcrab               =  "腐化猎头蟹是幼体猎头蟹和嗜血猎头蟹的结合体,更加强壮而且更快.\n它拥有AOE伤害抵抗,以及对人类施加sickness和dim vision的能力"
LANGUAGE.description_the_tickle_monster             =  "据说它是晚上躲在衣柜里把你从床上拖下来的怪物.长手梦魇的弹性手臂让人类极难逃脱,同时还使它成为理想的防线破坏者.\n攻击小物件时有伤害加成."
LANGUAGE.description_nightmare                      =  "一种极其罕见的变异赋予了梦魇异常的能力.\n梦魇在几乎所有方面都碾压了普通僵尸,拥有不容小视的力量.\n它的爪子一挥,就足以放倒几乎任何人."
LANGUAGE.description_darkmare                       =  "一种和梦魇较为相似但是稍弱的变体\n暗魇在几乎所有方面都碾压了普通僵尸,拥有不容小视的力量.\n它的爪子一挥,就足以放倒几乎任何人."
LANGUAGE.description_ancient_nightmare              =  "一个已经在这片大地上漫游许久的陈年梦魇.\n它的身体经过岁月的洗礼,变得更结实,机动性更弱,但在近距离遇敌时仍然很强大.\n在第4波以后会变得更加强大."
LANGUAGE.description_devourer                       =  "一种可怕的骨肉畸变体,有一根可投掷的肋骨,可刺入受害者体内将其卷走.\n它本身的速度并不快,但单独对付起来却非常危险."
LANGUAGE.description_abductor                       =  "一个腐烂的吞噬魔,擅长用能迅速武装的陷阱驱赶玩家.\n机动性很差,没有远程攻击,也没有自我治疗能力.\n紧密放置的陷阱可以相互连锁,将玩家或自己拖到很远的地方."
LANGUAGE.description_pukepus                        = "毒性气体充满了剧毒君王那溃烂的身躯.\n当心,它能够一次吐出几加仑的致命毒素"
LANGUAGE.description_bilemire                       = "剧毒君王的次级个体,但是它依旧让人头疼.\n它能够一次吐出大块的毒性物,相当危险!"
LANGUAGE.description_bonemesh                       = "面目全非的投骨者能够投掷血肉炸弹.\n每个炸弹都是由它身上的残骨烂肉组成,不仅可以伤害人类,同时也是其他丧尸宝贵的食物.\n投骨者还可以制造出和筑巢怪一样的巢穴来提高推进速度."
LANGUAGE.description_tarmesh                        = "投骨者的一种特殊次级个体.\n它能喷出把人类的枪支堵住,并且降低其准确性和射速的奇怪液体. \n并且依旧可以发射炸弹,对人类造成不小的伤害以及致盲,减慢该区域的人类,并提高丧尸的移动速度."
LANGUAGE.description_crow                           = "与感染前相比,现在的乌鸦更像是一种害虫.\n它们以感染者的腐肉为食,成为僵尸病毒的'携带者'"
LANGUAGE.description_wilowisp                       = "死者的灵魂.\n虽然威力不大,但能够致盲人类并在被杀死时产生致盲爆炸.\n不过微乎其微,几乎不会引起什么恐慌."
LANGUAGE.description_coolwisp                       = "来自北极的小精灵,能够用寒霜爆炸来干扰人类.\n寒霜会降低武器的射速和装弹速度"
LANGUAGE.description_zombie_torso                   = "一具还在爬行的僵尸躯干"
LANGUAGE.description_zombie_legs                    = "一双还在奔跑的僵尸大腿"
LANGUAGE.description_wraith                         = "这是僵尸还是幽灵?\n除了它独特的隐身能力和将眼前的一切切成丝儿的锋利的爪子之外,人类还知之甚少"
LANGUAGE.description_tormented_wraith               = "幽灵的一个更扭曲的变体.\n这种个体能够在受到伤害后变得疯狂,加快他们的攻击和移动.\n同时他们还能使用快速攻击.\n"
LANGUAGE.description_spectre                        = "更加可怕的幽灵变种.\n这种个体能够在受到伤害后变得疯狂,加速他们的攻击和移动.\n同时他们有强大的尖叫声,让那些靠近的人感到恐惧.\n"
LANGUAGE.description_fast_zombie_torso              = "一具还在爬行的奔跑僵尸躯干"
LANGUAGE.description_fast_zombie_torso_slingshot    = "一具弹射僵尸的躯干"
LANGUAGE.description_fast_zombie_legs               = "一双还在奔跑的奔跑僵尸大腿"
LANGUAGE.description_chem_fiend                     = "腐肉与有毒物质的结合体.\n每次挥动着利爪都会引起化学爆炸,造成一定范围伤害."
LANGUAGE.description_chem_burster                   = "生化破坏者的身体由具有挥发性的化学物质组成.\n每一次攻击都会将化学物质散布在防线上,当防线密集时效果拔群."
LANGUAGE.description_shade                          = "通过在自己周围创造一个强大的磁场来制造盾牌,直到盾牌被摧毁前,所有的子弹和投掷物都将对它无效.\n它们可以将任何没有钉住的物体以高速投向人类,以达到破坏性的效果."
LANGUAGE.description_frostshade                     = "寒霜万磁王制造的盾牌和投掷物比一般情况要弱,但一旦被击碎,它就能将人类冻伤.\n寒冷会减慢人类的行动并使他们的武器故障,射击速度变慢."
LANGUAGE.description_butcher                        = "一个疯狂的、不死的屠夫.它的身体强度并不高,但任何靠近它的\"幸运儿\"都很可能被撕成碎片."
LANGUAGE.description_gravedigger                    = "一个疯狂的、不死的守墓人.它挥舞着一把由墓地中发现的骨头制成的铲子."
LANGUAGE.description_flesh_creeper                  = "筑巢怪拥有创造巢穴的能力.\n其他僵尸会从这些巢穴中出现.巢穴的运行机制尚不清楚,但人类必须摧毁任何巢穴或筑巢怪."
LANGUAGE.description_flesh_weaver                   = "筑巢魔拥有创造巢穴的能力.\n其他僵尸会从这些巢穴中出现.巢穴的运行机制尚不清楚,但人类必须摧毁任何巢穴或筑巢魔."
LANGUAGE.description_gore_child                     = "一旦僵尸化,未出生的孩子也会被感染.\n他们没有特殊的能力,他们的力量来自于他们的数量."
LANGUAGE.description_giga_gore_child                = "血婴被放任太久的产物.\n恐怖的巨大身躯由僵化干细胞的作用下产生.\n它们还会成为血婴的宿主,血婴总是和它如影随形."
LANGUAGE.description_giga_shadow_child              = "一个腐化的血婴,具有遮蔽人类视线的能力.\n身体强度不如残暴血婴,但对近战武器有很高的抵抗力.\n它所生产的小血婴同样具有抗性,并且能够遮蔽视线."
LANGUAGE.description_shadow_gore_child              = "被黑暗腐化的血婴"
LANGUAGE.description_asskicker                      = "是时候踢爆人类并咬碎他们的屁股. \n我要将这世界上的屁股,一个不留的驱逐出去!"
LANGUAGE.description_shitslapper                    = "把你揍出屎来如何?"
LANGUAGE.description_doomcrab                       = "这个巨大的猎头蟹会跳到它的受害者身上,把他们压碎.\n同时有投掷厄运之球的能力,使人类变得虚弱.\n恐惧炸弹可以使附近的不死生物获得力量,并在一定延迟后爆炸."
LANGUAGE.description_extinctioncrab                 = "这个巨大的猎头蟹会跳到它的受害者身上,把他们压碎.\n同时有投掷厄运之球的能力,使人类变得虚弱."
LANGUAGE.description_red_marrow                     = "红细胞的异常增多是红骨身体颜色和大量喷洒血液的诱因.\n红骨在受到一定量伤害后身体表面会覆盖一层血盾,大幅减少受到的伤害."
LANGUAGE.description_cold_marrow                    = "一次事故使红骨的身体变得异常寒冷和易碎.\n通过提前储存在身体里的低温,冰骨在受到伤害时会释放一道冰波.\n但这也使得冰骨比红骨脆弱的多."
LANGUAGE.description_skeletal_walker                = "一具会动的骷髅,血量较少但对远距离伤害有更高抗性"
LANGUAGE.description_dread_knight                   = "它是一名强大的勇士,同时也是惧影卫队的召唤师,以活人的恐惧为食.\n它可以挥舞可怕的锤子击退敌人,并通过盟友和受害者的身体召唤仆从.\n面对近战浪人它也丝毫不为所动 .\n\n曾经它是对抗丧尸大军的十字军,但现在它也是巫妖的仆从之一"
LANGUAGE.description_dread_shadow                   = "惧影卫队的士兵,召唤他们需要一具肉体.随着波数他们也会逐渐强大起来,并且可以更有效的抵抗近战武器."
LANGUAGE.description_dread_fallen                   = "惧影卫队的士兵,召唤他们需要一具肉体.随着波数他们也会逐渐强大起来,并且可以更有效的抵抗近战武器.\n\n惧影狩猎者是暗影卫队的猎犬,它们无情地追捕任何一个战场上的逃兵."
LANGUAGE.description_dread_hulk                     = "惧影卫队的士兵,召唤他们需要一具肉体.随着波数他们也会逐渐强大起来,并且可以更有效的抵抗近战武器.\n\n即使是一具残破的尸体也可被作为容器..."
LANGUAGE.description_dread_brute                    = "惧影卫队的士兵,召唤他们需要一具肉体.随着波数他们也会逐渐强大起来,并且可以更有效的抵抗近战武器.\n\n惧影卫队士兵的种类并不单一,它们可以以任何容器为原型来生产战争机器."
LANGUAGE.description_dread_bloated                  = "惧影卫队的士兵,召唤他们需要一具肉体.随着波数他们也会逐渐强大起来,并且可以更有效的抵抗近战武器.\n\n有些容器体型会大于其他容器."
LANGUAGE.description_dread_grunt                    = "惧影卫队的士兵,召唤他们需要一具肉体.随着波数他们也会逐渐强大起来,并且可以更有效的抵抗近战武器.\n\n这些容器生前曾是剑士,盾卫或刽子手. 现在它们用手中的武器来毁灭一切."
LANGUAGE.description_dread_reaper                   = "惧影卫队的刽子手.随着波数而强化自己的魔法以及来自近战的抗性.\n当惧影卫队任需要更多的新成员时.\n恐惧收割者挥舞着它的镰刀,一次次完美解决了来自卫队的需求\n"
LANGUAGE.description_skeletal_shambler              = "一具巨大坚固的骨骼, 对远距离伤害有更高抗性.\n他们可以使用second wind."
LANGUAGE.description_skeletal_lurker                = "失去腿的枯骨行者.\n一具会动的骷髅,血量较少但对远距离伤害有更高抗性."
LANGUAGE.description_skeleton_warrior               = "来自远古时代的被遗忘的战士.他们携带的武器对于其他近战人员来说非常危险.他们用盾牌护卫时受到的伤害明显减少."
LANGUAGE.description_cinder_skeleton_warrior        = "来自远古时代的被遗忘的战士.他们携带的武器对于其他近战人员来说非常危险.他们用盾牌护卫时受到的伤害明显减少."
LANGUAGE.description_deadeye                        = "一个臭名昭著的雇佣兵弓箭手,被复生后继续为着不死者继续工作.\n它携带的短弓上布满倒勾以挂在血肉之中 同时燃烧箭头亦可点燃防线."
LANGUAGE.description_skeleton_archer                = "一名被遗忘在过去的弓箭手. /n使用弓箭与燃烧箭头将防线点燃."
LANGUAGE.description_skeleton_executioner           = "来自远古时期被人遗忘的刽子手.\n它携带的巨斧能像切菜一样砍下任何人的脖子.\n它还能释放斧刃风暴将附近的人砍成碎片."
LANGUAGE.description_ice_demon                      = "来自北境. 以给人带来痛苦为乐."
LANGUAGE.description_ice_devil                      = "来自北境. 为自己的杀人秀感到沾沾自喜的寒霜魔的领主."
LANGUAGE.description_shadow_lurker                  = "它很难在黑暗中被发现, 而且对近战攻击有更高抗性. 被击中的人类会获得exhaust和vision dimming debuff."
LANGUAGE.description_abyss_lurker                   = "一种抗性更高的暗影潜伏者, 可以投掷有confusion的深渊球."
LANGUAGE.description_shadow_walker                  = "一种机动性较差的暗影潜伏者.\n它很难在黑暗中被发现, 而且对近战攻击有更高抗性. 被击中的人类会获得exhaust和vision dimming debuff."
LANGUAGE.description_lacerator                      = "致残者那锋利的爪子可以给人类附加bleed和wound.\n通过弹射攻击它可以轻松追上猎物."
LANGUAGE.description_lacerator_charging             = "它有熊一样的身躯,冲撞起来却像狡兔一样灵敏.\n冲撞的力度之大,足以击倒任何人."
LANGUAGE.description_chem_charger                   = "它有熊一样的身躯,冲撞起来却像狡兔一样灵敏.\n冲撞的力度之大,足以击倒任何人.\n它的冲撞可以释放一种化学爆炸."
LANGUAGE.description_eradicator                     = "死亡和破坏的先锋. 铲除者强壮的身躯需要很强火力才能击垮.\n如果没有被爆头就很难被放倒."
LANGUAGE.description_annihilator                    = "由铲除者进化而来的死亡和破坏的化身.\n它对血肉和撕裂的渴望可以让它忘却疼痛.\n如果没有被爆头就很难被放倒."
LANGUAGE.description_brood_zombie                   = "各方面都比普通丧尸强一点."
LANGUAGE.description_howler                         = "可以发出尖锐咆哮的血肉泰坦.\n它的咆哮可以激化丧尸, 同时令周围人类陷入恐慌."
LANGUAGE.description_lich                           = "腐朽而狡猾的丧尸军团的一员,精通腐化的艺术.\n可以召唤产生强化僵尸的墓碑, 制造引力陷阱,还可以把墓碑中的僵尸召至身旁."
LANGUAGE.description_extinctioncrab                 = "Vile diseases churn within this giant headcrab.\nThe spores it spits will afflict those near it, reducing the effectiveness of healing."
LANGUAGE.description_corruptor                      = "腐化水晶中产生的怪胎.\n水晶不再是避难港——这种生物可以投掷一种可穿透人群的球体来使水晶腐化."
LANGUAGE.description_sigilite                       = "当水晶被腐化,他们被改造成畸形生物.\n这些生物可以放置标记,投射他们的能量,传送到上面并给建筑造成巨量伤害"
LANGUAGE.description_gunk_zombie                    = "身上不断流淌着黑色粘液的丧尸.\n其分泌的黏液可以阻塞枪支,降低枪支精准度和射速."
LANGUAGE.description_gunk_zombie_torso              = "一具还在爬行的粘液丧尸的躯干"
LANGUAGE.description_gunk_zombie_legs               = "一双还在奔跑的粘液丧尸的大腿"
LANGUAGE.description_gunk_fiend                     =  "来自黑色深渊.\n其分泌的黏液可以阻塞枪支,降低枪支精准度和射速."
LANGUAGE.description_gunk_fiend_torso               = "一具还在爬行的粘液魔鬼的躯干"
LANGUAGE.description_gunk_fiend_legs                = "一双还在奔跑的粘液魔鬼的大腿"
LANGUAGE.description_tar_monster                    = "来自黑色深渊.\n 其分泌的黏液可以阻塞枪支,降低枪支精准度和射速."
LANGUAGE.description_rune_watcher                   = "据说这种食腐生物经常被发现于长满腐化晶体的尸体上.\n其宿主基本不可能存活.\n然而,有极少数人观察到,只要其能从未被腐蚀的水晶能量中汲取养分,腐败就能让宿主活下去,并赋予其来自异世的力量.这是一种共生关系还是一种诅咒?"
LANGUAGE.description_viper                          = "一种罕见的感染物与毒蛇毒液产生突变的情况.宿主抑制毒液的能力,可致残猎物以拉近距离.擅长伏击打野人和融化无人防守的防线."
LANGUAGE.description_parasite                       = "由两个血腥生物组成的鲜红造物. 非常敏捷和危险, 可以击倒滞空的目标."
LANGUAGE.description_chemjuggernaut                 = "由生化破坏者进化出的怪物\n化学主宰的攻击带有一种挥发性化学物质, 被攻击的目标在受到其他种类的攻击时会产生爆炸反应."
LANGUAGE.description_brood_queen                    = "森林里的寄生女皇.\n成长到这个阶段的女性猎头蟹可以随性所欲的投掷并筑巢产卵\n他們令人毛骨悚然的哭聲會給任何人灌輸恐懼, 並將他們的後代引向潛在的獵物."
LANGUAGE.description_headcrab_hatchling             = "刚刚孵化出的小猎头蟹.\n弱小但无法忽视."
LANGUAGE.description_disruptor                      = "破坏者可以依靠体内的发电器官产生电能\n它可以远距离凝聚一种电场来破坏放置物."
LANGUAGE.description_ice_fiend                      = "极寒极黑的恶魔实体. \n它的爪子和掷出的黏着物均可frost and dim vision人类"
LANGUAGE.description_hemorrite                      = "不可想象,不可理解,与一具甚至不需要的肉体. \nHemorrite的身体让它可以随意分解与改造自己,这让Hemorrite可以传送到它的目的地.\n与有机物的接触使得Hemmorite在被击杀后会产生一些不稳定的剧烈反应."
LANGUAGE.description_bigghoul                       = "一个远古食尸鬼苏醒并挣脱了束缚它的躯壳. \n 当它绷紧肌肉时, 其孔武有力的躯体可以无视一切伤害"
LANGUAGE.description_the_lost                       = "它迷了..."
LANGUAGE.description_tickle_nightmare               = "这看起来像是你做过最糟糕的噩梦. 一个可怕的虚实,一个大部分人都没有见过的可怕生物."
LANGUAGE.description_hate                           = "一行人的喘息声回荡在锈迹斑斑的走廊上.我们终于从捕猎者手中逃脱出来.\n\n\"但我们失去了Petrovic....\".领队的的Sergei说到.一种恐惧感涌上我们的心头,因为我们已经跑得身心疲惫.突然间,墙壁和天花板上大喇叭的嘈杂声划破了寂静.\n\n\"先生们,恭喜你们!居然活到了现在.你们为了活命苟活至今,值得赞扬!那么让我们看看你们下一轮的表现吧!\"当大厅再次安静下来时,我们只能继续奔跑.大老远可以听到金属的摩擦以及的呻吟声,接着是低沉的轰隆声.尽管很困惑,但我们依旧没有停下来,直到轰隆声大到足以让我们认出它......\n\n\"是…柴油机吗?这个死胖子这次到底派了什么东西来对付我们."
LANGUAGE.description_sigil_tyrant                   = "在所有水晶生物中,这位似乎更加的敏锐,看起来它只想夺回一些什么东西.该不会是水晶吧?"
LANGUAGE.description_marrow_tyrant                  = "henry扛着枪,带着他老婆孩子去找个安全的地儿.吊车旁的旧集装箱引起了henry的注意,他准备让他的家人先在这避避难.\n\n\"听着,亲爱的,你和孩子待在这里,等我们把这些该死的僵尸清理干净,你们再出来.\"她点点头答应.\n\n\"但是爸爸,我不想呆在这...\"\n\n\"没事我的小甜心,我和你叔叔会保护你们的安全,这些墙壁非常坚硬.就算这些僵尸攻过来也不可能找到这.现在做个乖孩子好好待着,爸爸很快就回来,我保证!\"\n\n\"好吧...\"\n\n 在关紧集装箱大门后,henry召集剩下的兄弟,与朝家园袭来的僵尸殊死拼搏,在解决掉最后一只僵尸后,henry扔掉了枪转身奔向集装箱,在他打开大门后他惊恐的发现,集装箱背面就像罐头一样被切开了....\""
LANGUAGE.description_heresiarch                     = "** 开始回放 **\n\n\"这里是 AVALON-1,我已经到达指数位置,该区域已经被肃清.但有大量死亡的再生者,他们没装死,一个一个都检查过了. 但一定还有残余,因为它们都聚集得很近.\"\n\n\"AVALON-1 注意,指数没有显示任何生命体衰减迹象. 我们不能排除它们可能处于一种特殊的休眠状态,所以你必须得摧毁掉他们.\"\n\n\"明白了. 嘿,Connery ,把你的充能炸弹给我,我在那棵大树旁边的一堆僵尸那.\"\n\n\"收到.\" \"\n\n...\n\n\"为什么这树....它不是树!!!!\"\n\n在音频停止之前可以听到嘈杂的枪声.\n\n** 回放结束 **"
LANGUAGE.description_lesser_heresiarch              = "\"McKenzie,你看起来不太好.\"\n\n\"没事, 可能是在 PX 时候吃坏东西了. 反正我等一下还要去做\"消毒\"作业,如果有什么严重的事情他们会告诉我的.\"\n\n\"那又是什么? 我记得这是你这周第三次这样,他们也没给你安排其他事啊.\"\n\n\"那又咋样?世界上又没有后悔药可以吃.你又不是没见过,你不认真对待它会怎么对待你\"\n\n\"也是...你是对的,不好意思..我精神有点紧绷,一点鸡毛蒜皮的事都能让我倍感压力.\"\n\n\"别担心.晚点我会回来找你的.\"\n\n\"好吧......\"\n\n McKenzie 离开基地进入附近城市的废墟.他穿过被瓦砾覆盖的街道,进入了他的秘密基地.在昏暗的房间中央躺着他的猎物,被绑在一根柱子上,四肢和下巴都被切断了.他咧嘴笑着开始轻轻弹动起他的关节和脖子.\n\n\"让我们看看,也许我们’ 今天可以试试汽油.\""
LANGUAGE.description_gloom_walker                   = "开始记录.Drummond医生,斯坦福堡东区病房.日期:12月5日*静脉注射*病人:第二大队中尉Boris Kowalchik.今天第二次会议提到.在我们加大药效剂量后,中尉的精神状态已有恢复迹象,而他的身体状况也将在几日完全恢复.虽然之前的调查中.我们怀疑他的视力损害是由于直视烟雾信号导致,但在我们收集回来的样本解析完成前,我们都不能确定.在中尉回返前,预测他的视力恢复也能伴随他精神状态恢复过来,这样我们便更好了解他和他的队伍都发生了些什么."
LANGUAGE.description_lesser_gloom_walker            = "让这个世界再次充满幽暗的毁灭!"
LANGUAGE.description_bloodangel                     = "\"看吧,'驭血天使’.你不觉得这个名字很应景吗?它的侧翼膜就像翅膀那样——\"\n\n...\n\n\"是的,先生.\"\n\n...\n\n\"我明白,先生.\"\n\n...\n\n\"不,我们还没弄清楚为什么它的血液会有如此剧烈的反应.\"\n\n...\n\n\"那恐怕我们也无法恢复它们的理智了.\""
LANGUAGE.description_propmonster                    = "由于水晶的腐化,给予了这堆合金非凡的生命"
LANGUAGE.description_abhorrent_amalgam              = "合金和血肉组成的巨兽"
LANGUAGE.description_sanity_sentinel                = "水晶的魔法似乎在激荡着它"
LANGUAGE.description_flesh_sentinel                 = "他看起来好急"
LANGUAGE.description_spectral_revenant              = "一个沉睡多年,饱受折磨的灵魂决定从它永恒的梦境中醒来,带给世人来自他们精神深处的打击"
LANGUAGE.description_fetid_maw                      = "这只人见人恨的怪物散发着强烈的腐臭味,吐出的东西类似于它的远房表兄剧毒君王和剧毒魔.\n更糟糕的是,这种个体进化出了毒气囊,使其能飞在空中,并且能够从上方将毒气当作炸弹一样投掷下去"
LANGUAGE.description_gonome                         = "你能想象下一阶段的突变又会是什么样子吗?\n似乎只要猎头蟹和它们的宿主共生的够久,僵尸就会进化成脓包猎头者.\n宿主的整体体重都会增加,而且他们拥有了更高的机动性和投掷谜之肉块的能力"
LANGUAGE.description_harbinger                      = "最后一只被目击到的脓包猎头鬼变异个体,也是迄今为止最致命的变异体……"
LANGUAGE.description_breachprowler                  = "来自世界之外的存在....它徘徊在现实的边缘....期待着侵入"
LANGUAGE.description_fleshfire                      = "一只浑身充满易燃化学物的火焰怪物\n攻击会点燃玩家并对防线造成巨大伤害."
LANGUAGE.description_dreadmammoth                   =  "敏捷又恐怖"
LANGUAGE.description_hulk         = "一只变异的毒丧尸,不仅腿劲很强,耳朵也很长.\n是什么嬉皮士吗?"
LANGUAGE.description_cinder_thug          = "一个被火山岩,煤渣和岩浆覆盖的强大生物.冲刺时它的体温近乎提高2000摄氏度左右,更是有毁天灭地般的冲击力,以至于那些灼热的碎片会覆盖在它那崎岖的外表上.目前对cinder thug以及其喜好破坏的习性知之甚少."
LANGUAGE.description_cinder_ghoul          = "一个全身充斥着熔岩与火花的食尸鬼. 身体表现出一种罕见的特性, 可以让它产生高温肉块. 在承受足够的伤害后,体内的热能会使食尸鬼的身体变热,大大提高移动速度和攻击速度"
LANGUAGE.description_alphacrab           = "一种巨大的变种猎头蟹,会跳到受害者的身上碾碎他们.\n具有投掷孢子的能力,可以治愈丧尸并伤害人类."
LANGUAGE.description_meteoric_eradicator           = "与熔岩融为一体,这种进化的铲除者能够点燃路障和人类,以及可以投掷火焰石.\n但同样的,他们似乎退化了原本铲除者的特性"
LANGUAGE.description_pigeon                 = "一只讨人厌的小鸟,会往人类的头上拉屎"
LANGUAGE.description_seagull                = "一只机智的小鸟,去码头整点人类扔在地上的物品"
LANGUAGE.description_banished_warrior       = "一个被时代遗忘的勇士,被一个腐蚀了他思想和灵魂的力量唤醒了.但是他掌控并为己所用.\n 据说这种个体能够从红色的驱逐水晶中汲取巨大的力量. 然后追捕那些遇到他的倒霉蛋"
LANGUAGE.description_tickle_torment       = "这些长爪的怪物已经适应了黑暗,能够数个月不见于日光之下/它们最为醒目的特征是发光的红眼,而它们长爪的每一次刺击都使得它们变得更强."
LANGUAGE.description_chem_jaeger       = "长年暴露在辐射下，使得本就摧枯拉朽的化学主宰进化为了更为恐怖的生化猎手. 这些强大的僵尸能够轻易地摧毁障碍物,并用它腐蚀性的利爪毒杀附近所有的人类."
LANGUAGE.description_ice_marrow          = "蛰伏在长年累月的大暴风雪中, 冰骨可能会发生一次冻结变化。这些最近才被发现的冻骨比冰骨更为强大，并且能够冻结物体。."
LANGUAGE.description_tormentor          = "注入了噩梦般的精华物质后, 这些被称为折磨者的存在比起腐晶魔更为强大。 它们投射出的物质能使水晶腐化地更快，并使人类进入梦魇状态."
LANGUAGE.description_restlesszombie     = "一种严重退化却不眠不息的僵尸。 \n它在彻底安眠之前会数次苏生。"
LANGUAGE.description_behemoth           = "那些死者最后感受到的是这无头巨物的千钧重压，随后是撬棍迅捷的碎颅一击。名为贝西摩斯的怪物能够发射出不稳定的肉球炸弹以及强力的撬棍，借此它能够毫不费力的飞上天空，瞬间碾碎一切粗心的可怜虫。"

LANGUAGE.description_dread_monger       = "Nothing has been found about this creature yet."
LANGUAGE.description_amalgam            = "Nothing has been found about this creature yet."
LANGUAGE.description_moroi              = "第一天: 对某些存在来说，似乎这黑森林并不足够黑暗。近来我注意到我所居住的小木屋附近有一些异样的动静。 尽管这里足够安全，能够避开大部分僵尸，我还是感觉不够安全。\n\n第四日: 在那些动静开始后，我不断地做着噩梦，情况越来越糟。 我担心也许我来不及拯救自己了，但我还是会尽一切可能逃出着该死的黑森林。\n\n第五日: 我被窗外一阵响声惊醒。 我胆战心惊不敢看它，心中油然而生一阵恐惧，但我的好奇心最终驱使着我前去查看。 我悄悄地望向窗外，在那一瞬间死神似乎闯进了我的脑海。 我看见一只干瘦的、黑红相间的，似乎没有头颅的人形生物. 我战栗到不知所措，而它也发现了我.注视我许久后它迅速的逃进了森林中. 我这才知道现在逃亡已经太晚了。"
LANGUAGE.description_elemental          = "对于我来说，水晶永远是个谜. 它们何时才会出现? 为何它们要保护我们? 那些丧尸又为何要得到它? 我们设立了一个小组来保护据点附近的一个水晶. 一小时过去了,一个士兵嘀咕道, \"什么也没发生，为什么我们还要在这看着这破烂玩意?\".\n\n许久之后，我们突然听到了外面传来一声非人般的惨叫. \"那他妈是什么玩意??\" 一名士兵惊恐地呼喊. 那个东西就像是个腐化的水晶变成了活体一般. \"开火，开火!\", 我声嘶力竭地喊道. 向那个生物开火似乎只是在激怒它，而它随后开始投掷爆炸物攻击我们。 我叫喊着撤退但为时已晚。 爆炸杀死了其他所有人。我勉强活了下来，但还是迅速躲了起来。等到一切归于平静，我回头检查了战场。那个腐化了的水晶消失了，剩下的只有满地的绿色水晶碎片。看来僵尸并非我们唯一需要面对的威胁。 "
LANGUAGE.description_frostbite          = "\"又一场暴风雪，哈\", 我对如此剧烈的天气变化感到奇怪 \"Samantha!\", 我大声喊道. \"干嘛?\", 她回应道. \"又一场暴风雪，你知道我们该怎么做\", 我说. 她咕哝道 \"又来?\", 起身离开沙发后她合上了房间内所有的窗帘. 在她做这些事情时,我出门去清理了一些积雪,这时我听到了远方传来了一阵怪异的闷哼. 在数分钟对附近的检查后，我找到了声音的源头.我从未见过这样的...东西. 它好像一个幽魂从冥界闯进人间，那泛着浅蓝色的形体仿佛漂浮在空中. 我凑上前去仔细查看，它也注意到了我, 随后发出同样的，但更响亮的叫声，然后开始追逐我。我慌忙向屋子跑去，迅速地打开然后又关上屋前的大门。 \"你还好吗?\" Samantha担忧地对我说。 我走向她,抓住她的肩膀，用严肃的眼神对着她 \"我们得走了\"."
LANGUAGE.description_nuclear_terror     = "核爆后留下了一片废土。这场毁灭性的灾难发生后的许多年，大多数的城市再也没有外来的探索者，也许外面的人类早已灭绝。\"啊，我得走了\", 我自语道. 我得回到我的避难所了.\n\n花费了好一会儿，我最终到了安全屋外. 我注意到外面的守卫消失了,是我离开的时候发生了什么吗?我走进内部进行搜查，只发现了一堆尸体,其中一个格外的发绿且臃肿。 我被眼前的场景惊吓到了，但使我更震惊的是它居然缓缓地站了起来.我惊恐地向外面的马路跑去. 我停下来休息片刻，但它仍在不停地追逐着我. 这么短的时间里究竟是怎么发生这一切的?"
LANGUAGE.description_poison_anomaly     = "Nothing has been found about this creature yet."
LANGUAGE.description_gonarch            = "Nothing has been found about this creature yet."
LANGUAGE.description_tickledecimator    = "Nothing has been found about this creature yet."

-- Class control schemes
LANGUAGE.controls_zombie                = "> PRIMARY: 攻击\n> SECONDARY: 快速攻击\n> RELOAD: 嚎叫\n> SPRINT: 装死\n> 致命一击位于腿部: 复活/转化为爬行尸或丧尸腿"
LANGUAGE.controls_zombie_ichor          = "> PRIMARY: 攻击\n> SECONDARY: 投掷减射速粘液\n> RELOAD: 嚎叫\n> SPRINT: 装死"
LANGUAGE.controls_poison_zombie         = "> PRIMARY: 攻击\n> SECONDARY: 投掷poison血肉\n> RELOAD: 嚎叫"
LANGUAGE.controls_wild_poison_zombie    = "> PRIMARY: 攻击\n> SECONDARY: 投掷poison血肉\n> RELOAD: 嚎叫"
LANGUAGE.controls_fast_zombie           = "> PRIMARY: 攻击\n> SECONDARY: 跃击/ 攀爬\n> RELOAD: 嚎叫\n> 致命一击位于腿部: 转化为奔跑腿或奔跑爬行尸"
LANGUAGE.controls_crimson_render        = "> PRIMARY: Serrated 攻击\n> SECONDARY: 跃击/ 攀爬\n> RELOAD: 投掷bleed血肉\n> ON FATAL HIT IN LEGS: 转化为奔跑腿或奔跑爬行尸"
LANGUAGE.controls_fast_zombie_slingshot = "> PRIMARY: 攻击\n> SECONDARY: 弹射/ 攀爬\n> RELOAD: 嚎叫\n> 弹射击中人类: 减速"
LANGUAGE.controls_parasite              = "> PRIMARY: 吸血攻击\n> SECONDARY: 跃击/ 攀爬\n> RELOAD: 狂暴\n> 狂暴状态下: 增加攻速/移速, 减少跃击延迟和冷却时间"
LANGUAGE.controls_bloated_zombie        = "> PRIMARY: 吸血攻击\n> SECONDARY:嚎叫n\n> SPRINT: 装死\n> 死亡时: 向四周溅射肉片,回复周围丧尸血量"
LANGUAGE.controls_vile_monster          = "> PRIMARY: 攻击\n> SECONDARY: poison 呕吐物\n> SPRINT: 装死"
LANGUAGE.controls_fresh_dead            = "> PRIMARY: 攻击\n> SECONDARY: 嚎叫\n> SPRINT: 装死"
LANGUAGE.controls_agile_dead            = "> PRIMARY: 攻击\n> SECONDARY: 攀爬"
LANGUAGE.controls_super_zombie          = "> PRIMARY: 攻击\n> SECONDARY: 跃击/ 攀爬"
LANGUAGE.controls_ze_zombie             = "> PRIMARY: 攻击\n> SECONDARY: 嚎叫\n> SPRINT: 装死"
LANGUAGE.controls_ghoul                 = "> PRIMARY: Poison 攻击\n> SECONDARY: 投掷减速黏着物\n> SPRINT: 装死\n> RELOAD: 嚎叫\n> 击中人类时: enfeeble"
LANGUAGE.controls_venerableghoul        = "> PRIMARY: Poison 攻击\n> SECONDARY: 投掷enfeeble头骨\n> SPRINT: 装死\n> RELOAD: 嚎叫\n> 击中人类时: 减速"
LANGUAGE.controls_frostbittenghoul      = "> PRIMARY: Winter's Curse 攻击\n> SECONDARY: 投掷Winter's Cursed 冰球\n> SPRINT: 装死\n> RELOAD: 嚎叫\n> 击中人类时: Slow, Frost and Winter's Curse"
LANGUAGE.controls_chilled_ghoul         = "> PRIMARY: Frost 攻击\n> SECONDARY: 投掷霜冻黏着物\n> SPRINT: 装死\n> RELOAD: 装死\n> 击中人类时: Frost"
LANGUAGE.controls_frigid_revenant       = "> PRIMARY: Frost and blind 攻击\n> SECONDARY: 投掷霜冻致盲黏着物\n> 击中人类时: Frost, dim vision, and exhaustion"
LANGUAGE.controls_elderghoul            = "> PRIMARY: Poison 攻击\n> SECONDARY: 投掷poison血肉\n> RELOAD: 嚎叫\n> 受到伤害时: 向四周喷射poison"
LANGUAGE.controls_noxiousghoul          = "> PRIMARY: Poison 攻击\n> SECONDARY: 投掷poison,slow,sickness血肉\n> RELOAD: 嚎叫\n> 受到伤害时: 向四周喷射poison\n> 击中人类时: enfeeble"
LANGUAGE.controls_headcrab              = "> PRIMARY: 跃击\n> RELOAD: 潜地\n> SPRINT: 冲刺"
LANGUAGE.controls_fast_headcrab         = "> PRIMARY: 跃击"
LANGUAGE.controls_bloodsucker_headcrab  = "> PRIMARY: 跃击\n> 击中人类时: Bleed 并恢复自身少量血量"
LANGUAGE.controls_poison_headcrab       = "> PRIMARY: 跃击\n> SECONDARY: 投射毒针\n> 毒针击中人类时: Increased Poison DOT\n> 跃击击中人类时: Poison\n> 跃击击中人类头部时: Blind\n> RELOAD: 嚎叫\n> SPRINT: 冲刺"
LANGUAGE.controls_barbed_headcrab       = "> PRIMARY: 跃击\n> SECONDARY: 投射毒针\n> 毒针击中人类时: Increased Poison DOT\n> 跃击击中人类时: Poison\n> 跃击击中人类头部时: Blind\n> RELOAD: 毒针扫射\n> SPRINT: 冲刺"
LANGUAGE.controls_carrion_headcrab      = "> PRIMARY: 跃击\n> 击中人类时: Bleed and heal for a small amount of health, on top of applying dim vision\n> RELOAD: 潜地"
LANGUAGE.controls_the_tickle_monster    = "> PRIMARY: 攻击\n> SECONDARY: 嚎叫"
LANGUAGE.controls_nightmare             = "> PRIMARY: 攻击\n> SECONDARY: 快速攻击\n> SPRINT: 暗影步\n> SPRINT WHILE SHADOW RUN: 梦魇爆破\n> 击中人类时: 下一次攻击同一目标时伤害+4.5"
LANGUAGE.controls_darkmare              = "> PRIMARY: 攻击\n> SECONDARY: 快速攻击\n> SPRINT: 暗影步\n> SPRINT WHILE SHADOW RUN: 梦魇爆破\n> 击中人类时: 下一次攻击同一目标时伤害+2.5"
LANGUAGE.controls_ancient_nightmare     = "> PRIMARY: 攻击\n> SECONDARY: 冲刺\n> 击中人类时: 赋予梦魇状态,减少梦魇迷雾冷却时间\n> 击中防线时: 下一次击中防线时造成的伤害提高, 减少梦魇迷雾冷却时间\n> RELOAD: 释放梦魇迷雾\n> 处于梦魇迷雾中时: 变得难以看清且无声\n> SPRINT: 标记"
LANGUAGE.controls_devourer              = "> PRIMARY: 攻击\n> SECONDARY: 释放勾爪\n> RELOAD: 酸液喷吐\n> SPRINT: 放置陷阱"
LANGUAGE.controls_abductor              = "> PRIMARY: 攻击\n> SECONDARY: 放置陷阱\n> RELOAD: Self-target traps"
LANGUAGE.controls_pukepus               = "> PRIMARY: 呕吐\n> SECONDARY: 投掷毒球\n> 受到伤害时: 向四周喷射poison\n> 死亡时: Poison 爆炸"
LANGUAGE.controls_bonemesh              = "> PRIMARY: 攻击\n> SECONDARY: 投掷医疗肉球\n> RELOAD: 投掷大医疗肉球\n> SPRINT: 建造巢穴"
LANGUAGE.controls_wraith                = "> PRIMARY: 攻击\n> RELOAD: 嚎叫\n> 隐身程度取决于移速和观察距离"
LANGUAGE.controls_tormented_wraith      = "> PRIMARY: 攻击\n> RELOAD: 嚎叫\n> SECONDARY: 快速攻击\n> 隐身程度取决于移速和观察距离\n> 低于70HP时狂暴"
LANGUAGE.controls_spectre               = "> PRIMARY: 攻击\n> SECONDARY: 快速攻击\n> RELOAD: 嚎叫\n> 隐身程度取决于移速和观察距离\n> 低于150HP时狂暴"
LANGUAGE.controls_chem_fiend            = "> PRIMARY: AoE 攻击\n> SECONDARY: 嚎叫"
LANGUAGE.controls_chem_burster          = "> PRIMARY: AoE 攻击\n> SECONDARY: 嚎叫"
LANGUAGE.controls_shade                 = "> PRIMARY: 投掷物体\n> SECONDARY: 举起物体\n> RELOAD: 召唤岩石\n> ZOOM: 万磁脉冲\n> SPRINT: 举盾\n> 盾破坏时: 周围丧尸获得shield"
LANGUAGE.controls_frostshade            = "> PRIMARY: 投掷物体\n> SECONDARY: 举起物体\n> RELOAD: 召唤冰块\n> ZOOM: 万磁脉冲\n> SPRINT: 举冰盾\n> 盾破坏时: 周围丧尸获得shield"
LANGUAGE.controls_butcher               = "> PRIMARY: 吸血攻击\n> 击中人类时: 累积rage槽,增快攻速\n> SECONDARY: 投掷厨刀\n> 被厨刀击中时: Maim, Prey debuff and build Rage\n> RELOAD: Enrage\n> ENRAGE状态时: 提高自身和周围丧尸的攻速和移速"
LANGUAGE.controls_gravedigger           = "> PRIMARY: 攻击\n> HOLD PRIMARY: 蓄力攻击\n> 攻击爆头时: 更高伤害\n> SECONDARY: 投掷铲子\n> RELOAD: 挖墓碑\n> 墓碑: 经过墓碑的丧尸增加攻速和移速.\n> 墓碑被摧毁时: 周围丧尸获得Enrage, 周围人类获得prey和dim vision."
LANGUAGE.controls_flesh_creeper         = "> PRIMARY: 攻击\n> SECONDARY: 建巢\n> RELOAD: 飞跃\n> SPRINT: 喷射肉汁,喷射速度和精准度逐渐提高\n> 被肉汁击中: Anchor"
LANGUAGE.controls_gore_child            = "> PRIMARY: 攻击"
LANGUAGE.controls_giga_gore_child       = "> PRIMARY: Smash\n> SECONDARY: Throw Gore Child bomb\n> RELOAD: Cry\n> ON CRY: Greatly increased movement speed. Slow & Prey humans. Teleport all children to self"
LANGUAGE.controls_giga_shadow_child     = "> PRIMARY: Smash\n> SECONDARY: Throw Shadow Child bomb\n> RELOAD: Obscuring Knockdown Cry\n> ON HIT: Dim Vision\n> ON HIT BY MELEE: Resist damage> PRIMARY: Smash\n> SECONDARY: Throw Shadow Child bomb\n> RELOAD: Obscuring Knockdown Cry\n> ON HIT: Dim Vision\n> ON HIT BY MELEE: Resist damage"
LANGUAGE.controls_shadow_gore_child     = "> PRIMARY: Claws\n> ON HIT: Dim Vision\n> ON HIT BY MELEE: Resist damage"
LANGUAGE.controls_asskicker             = "> PRIMARY: 左鞭腿\n> SECONDARY: 右鞭腿"
LANGUAGE.controls_shitslapper           = "> PRIMARY: 掌击\n> RELOAD: 崛地而起\n> SPRINT: 蓄力\n> 崛地而起时: 造成小型地震并将你自己和周围人类震至空中.\n> 蓄力时: 下一次攻击击倒人类3秒."
LANGUAGE.controls_doomcrab              = "> PRIMARY: Leap attack\n> SECONDARY: Doom ball\n> RELOAD: Dark nova on self"
LANGUAGE.controls_red_marrow            = "> PRIMARY: 攻击\n> SECONDARY: 血盾\n> 血盾状态下: 减少伤害, 增加移速, 周围僵尸回复血量并免疫debuff  \n> 血盾周围的人类: 被吸收血甲的同时获得boiling blood和bleed. 自身根据吸收血甲的量获得battlecry. \n> ON HIT BARRICADE: Life Leech Curse\n> RELOAD: 标记"
LANGUAGE.controls_skeletal_walker       = "> PRIMARY: 攻击\n> SECONDARY: 嚎叫\n> RELOAD: 嚎叫\n> SPRINT: 装死\n> 受到远距离攻击: 大幅减少受到的伤害"
LANGUAGE.controls_dread_shadow          = "> PRIMARY: 攻击\n> SECONDARY: 嘲讽\n> 受到近战武器攻击: 减少受到的伤害"
LANGUAGE.controls_dread_grunt           = "> PRIMARY: 攻击\n> SECONDARY: 嘲讽\n> 受到近战武器攻击: 减少受到的伤害"
LANGUAGE.controls_dread_bloated         = "> PRIMARY: 攻击\n> SECONDARY: 嘲讽\n> 受到近战武器攻击: 减少受到的伤害"
LANGUAGE.controls_dread_brute           = "> PRIMARY: 攻击\n> SECONDARY: 嘲讽\n> 受到近战武器攻击: 减少受到的伤害"
LANGUAGE.controls_dread_fallen          = "> PRIMARY: 攻击\n> SECONDARY: Lunging Claws\n> 击中人类时: 附加Dread\n> RELOAD: 嚎叫"

LANGUAGE.controls_tickle_torment        = "> PRIMARY: Torment Claws\n> SECONDARY: Tickle"
LANGUAGE.controls_chem_jaeger           = "> PRIMARY: AoE Claws\n> ON HIT OBJECT: Explosive Residue\n> SECONDARY: Charge\n> ON SPAWN: 20 seconds of acid claws"
LANGUAGE.controls_deadeye               = "> PRIMARY: Fire Arrow\n> SECONDARY: Arrow Stab\n> RELOAD: Burning Arrow Multishot\n>ON HIT AT LONG DISTANCE: Take less damage\n> ON ARROW HEADSHOT: Bonus damage"
LANGUAGE.controls_skeleton_archer       = "> PRIMARY: Fire Arrow\n> SECONDARY: Arrow Stab\n> RELOAD: Burning Arrow Multishot\n>ON HIT AT LONG DISTANCE: Take less damage\n> ON ARROW HEADSHOT: Bonus damage"
LANGUAGE.controls_alphacrab             = "> PRIMARY: Leap attack\n> SECONDARY: Throw Blood Spores\n> RELOAD: Blood Puddle"
LANGUAGE.controls_ice_marrow            = "> PRIMARY: Ice Claws\n>ON PROP HIT: Prop Freeze\n> SECONDARY: Ice Shield\n> ICE SHIELD: Reduce damage taken while applying frost to nearby humans.\n> RELOAD: Throws 6 Piercing Ice globes"
LANGUAGE.controls_tormentor             = "> PRIMARY: Nightmare Claw\n> SECONDARY: Nightmare Orb\n RELOAD: Nightmare Beam\n NIGHTMARE BEAM: Damage Humans and Props"
LANGUAGE.controls_primalghoul           = "> PRIMARY: Poison claws\n> SECONDARY: Throw disabling goop\n> RELOAD: Battlecry and Rally Howl\n> ON DAMAGE TAKEN: Poison spray\n> ON HIT HUMAN: Enfeeble\n> ON HIT BARRICADE: Mark Prop"
LANGUAGE.controls_restlesszombie        = "> PRIMARY: Claws\n> SECONDARY: Moan"

LANGUAGE.controls_skeletal_shambler     = "> PRIMARY: 攻击\n> SECONDARY: 嚎叫\n> RELOAD: 嚎叫\n> SPRINT: 装死\n> 受到远距离攻击: 大幅减少受到的伤害\n> 致命一击位于腿部: 复活"
LANGUAGE.controls_skeletal_lurker       = "> PRIMARY: 攻击\n> SECONDARY: 嚎叫\n> 受到远距离攻击: 大幅减少受到的伤害"
LANGUAGE.controls_skeleton_executioner  = "> PRIMARY: 攻击\n> HOLD PRIMARY: 蓄力攻击\n> 击中人类时: Bleed\n> SECONDARY: 斧刃风暴\n>被斧刃风暴击中: Slow and Enfeeble\n> RELOAD: 嘲讽\n> 攻击爆头时: 更高伤害\n>"
LANGUAGE.controls_dread_reaper          = "> PRIMARY: C攻击\n> HOLD PRIMARY: 重击\n> 击中人类时: Bleed, Dread\n> SECONDARY: Whirlwind\n>ON WHIRLWIND PARRY: Slow and Enfeeble\n> RELOAD: 投射物l\n> ON HEADSHOT: 额外伤害"

LANGUAGE.controls_dread_knight          = "> PRIMARY: 攻击\n> HOLD PRIMARY: 蓄力攻击\n> 击中人类时: Dread\n> 蓄力攻击击中人类时: Sap stamina, slow and knockback all other nearby humans\n> SECONDARY: Shatter\n> RELOAD: Dread附近僵尸并给自己护甲\n> SPRINT: Rallying Mark\n> RALLY: +10%移速"
LANGUAGE.controls_ice_demon             = "> PRIMARY: 攻击\n> 击中人类时: Winter's Curse, Frost\n> SECONDARY: 冰冷二重身\n> 人类被DOPPELGANGER击中时: Frozen, Winter's Curse\n>ON HIT BY UNDEAD: Launch Ice Shards\n> RELOAD: Ice Puddle\n>ON TOUCH HUMAN: Knocked Down, Heavy damage when knocked into doppelganger"
LANGUAGE.controls_ice_devil             = "> PRIMARY: Ice Claws\n> ON HIT HUMAN: Winter's Curse, Frost\n> SECONDARY: Frozen Doppelganger\n> ON HUMAN TOUCH DOPPELGANGER: Frozen, Winter's Curse\n>ON HIT BY UNDEAD: Launch Ice Shards\n> RELOAD: Ice Puddle\n>ON TOUCH HUMAN: Knocked Down, Heavy damage when knocked into doppelganger\n> SPRINT: Winter's Howl\n> ON HOWL: Slow, Frost Humans, Buff Undead attacks with Winter's Curse, Bleed"
LANGUAGE.controls_skeleton_warrior      = "> PRIMARY: 攻击\n> 击中人类时: Bleed\n> SECONDARY: 举盾\n> 被盾招架时: Slow and Enfeeble\n> 举盾时: 抵消绝大部分伤害\n> 受到远距离攻击: 大幅减少受到的伤害\n> 举盾时被攻击: 自动招架近战武器的攻击"
LANGUAGE.controls_cinder_skeleton_warrior   = "> PRIMARY: 攻击\n> 击中人类时: Bleed & Fire\n> SECONDARY: 举盾\n> 被盾招架时: Slow and Enfeeble\n> 举盾时: 抵消绝大部分伤害\n> 受到远距离攻击: 大幅减少受到的伤害\n> 举盾时被攻击: 自动招架近战武器的攻击"

LANGUAGE.controls_deadeye               = "> PRIMARY: 射箭\n> SECONDARY: 箭矢捅人\n> RELOAD: 燃烧箭连射\n> 远距离射中: 伤害变低\n> 射中头部: 额外伤害"
LANGUAGE.controls_skeleton_archer       = "> PRIMARY: 射箭\n> SECONDARY: 箭矢捅人\n> RELOAD: 燃烧箭连射\n> 远距离射中: 伤害变低\n> 射中头部: 额外伤害"

LANGUAGE.controls_wilowisp              = "> PRIMARY: 闪光致盲\n> RELOAD: 嚎叫\n> 死亡时: 闪光爆炸"
LANGUAGE.controls_coolwisp              = "PRIMARY: 寒霜脉冲\n> RELOAD: 嚎叫\n> ON DEATH: 寒霜爆炸"
LANGUAGE.controls_shadow_lurker         = "> PRIMARY: 攻击\n> 人类受到攻击时: Dim Vision and Exhaustion\n> 被近战武器击中时: 减少受到的伤害"
LANGUAGE.controls_abyss_lurker          = "> PRIMARY: 攻击\n> 人类受到攻击时: Dim Vision and Exhaustion\n> SECONDARY: 投掷致盲球\n> 被近战武器击中时: 减少受到的伤害"
LANGUAGE.controls_lacerator             = "> PRIMARY: 攻击\n> SECONDARY: 跃击\n> 攻击bleeding人类: 根据bleed数量赋予wound\n> RELOAD: 嚎叫"
LANGUAGE.controls_lacerator_charging    = "> PRIMARY: 流血攻击\n> 击中人类时: Bleed\n> SECONDARY: 冲撞\n> RELOAD: 嚎叫"
LANGUAGE.controls_chem_charger          = "> PRIMARY: 流血攻击\n> 击中人类时: Bleed\n> SECONDARY: 冲撞\n> RELOAD: 嚎叫\n> 冲撞效果: AOE爆炸"
LANGUAGE.controls_eradicator            = "> PRIMARY: 攻击\n> SECONDARY: 快速攻击\n> RELOAD: 嚎叫\n> 致命攻击不是爆头时: 复活"
LANGUAGE.controls_annihilator           = "> PRIMARY: Shielding Claws\n> SECONDARY: 嚎叫\n> 致命攻击不是爆头时: 复活"
LANGUAGE.controls_howler                = "> PRIMARY: 攻击\n> SECONDARY: 咆哮\n> RELOAD:嚎叫并标记\n> BELLOW: 赋予周围僵尸护甲."
LANGUAGE.controls_lich                  = "> PRIMARY: 释放法术\n> SECONDARY: 切换法术\n> RELOAD: 瞬移"
LANGUAGE.controls_extinctioncrab        = "> PRIMARY: Leap Attack\n> SECONDARY: Extinction Spore"
LANGUAGE.controls_corruptor             = "> PRIMARY: 攻击\n> SECONDARY: 腐化球\n RELOAD: 腐化射线\n 腐化射线: 对prop和人类造成伤害"
LANGUAGE.controls_cold_marrow           = "> PRIMARY: 冰攻击\n> SECONDARY: 冰护甲\n>冰护甲: 减少受到的伤害并将周围人类frost.\n> RELOAD: 投掷冰球"
LANGUAGE.controls_sigilite              = "> PRIMARY: Rock Claw\n> ON HIT: Shattered\n> SECONDARY: Corrupt Beam\n CORRUPT BEAM: Damage Humans and Props, Gives Shield RELOAD: Place Sigil Marker\n> Q: SWITCH SPRINT ABILITIES\n> SPRINT 1: Create/Teleport to projection\n> SPRINT 2: Create/Teleport to projection or Teleport to Sigil Marker or Corrupted Sigil"
LANGUAGE.controls_gunk_zombie           = "> PRIMARY: Gunk攻击\n> SECONDARY: 投掷gunk球\n> 死亡时: Gunk爆炸"
LANGUAGE.controls_gunk_fiend            = "> PRIMARY: Gunk攻击\n> SECONDARY: 投掷gunk球\n> 死亡时: Gunk爆炸"
LANGUAGE.controls_tar_monster           = "> PRIMARY: Gunk 攻击\n> SECONDARY: 投掷gunk球\n> 投掷gunk球时死亡时: Gunk爆炸"
LANGUAGE.controls_rune_watcher          = "> 飞行时PRIMARY: 冲刺\n> SECONDARY: 起飞"
LANGUAGE.controls_gunk_zombie_torso     = "> PRIMARY: Gunk 攻击\n> SECONDARY: 投掷gunk球"
LANGUAGE.controls_gunk_zombie_legs      = "> PRIMARY: 左踢腿\n> SECONDARY: 右踢腿"
LANGUAGE.controls_viper                 = "> PRIMARY: Acid Claws\n> SECONDARY: Spit Corrosive Acid\n> RELOAD: Launch Grapple Tongue\n> SPRINT: Proximity-based Sticky Traps\n> ON GRAPPLE SURFACES: Pull self and stick\n> ON GRAPPLE PROPS: Pull towards self"
LANGUAGE.controls_chemjuggernaut        = "> PRIMARY: AoE 攻击\n> 攻击props时: 爆炸攻击\n> SECONDARY: 冲撞"
LANGUAGE.controls_brood_queen           = "> PRIMARY: Leap attack\n> SECONDARY: Headcrab nest\n> RELOAD: Mark targets\n> SPRINT: Burrow"
LANGUAGE.controls_headcrab_hatchling    = "> PRIMARY: 攻击"
LANGUAGE.controls_disruptor             = "> PRIMARY: 攻击\n> 击中人类时: Corrupted Thorns and Tremors\n> SECONDARY: 破坏球\n RELOAD: 破坏射线\n 破坏射线: 减少目标血甲, 对prop和人类造成伤害"
LANGUAGE.controls_primeghoul            = "> PRIMARY: Poison 攻击\n> SECONDARY: 投掷poison,slow,sickness血肉\n> RELOAD: 战吼\n> 受到伤害时: 向四周喷射poison\n> 击中人类时: enfeeble\n> 攻击防线时: 标记"
LANGUAGE.controls_hemorrite             = "> PRIMARY: Rock Claw\n> ON HIT: Shattered\n> SECONDARY: Disrupt Beam\n DISRUPT BEAM: Drain Blood Armor, Damage Humans and Props, Gives Shield\n RELOAD: Place Flesh Beacon\n> Q: SWITCH SPRINT ABILITIES\n> SPRINT 1: Create/Teleport to projection\n> SPRINT 2: Create/Teleport to projection or Teleport to Flesh Beacon or Corrupted Sigil\n> ON HIT BARRICADE: Life Leech Curse"
LANGUAGE.controls_bigghoul              = "> PRIMARY: 攻击/ 投掷\n> SECONDARY: 抓起 / 释放\n> RELOAD: 秀肌肉\n> 击中人类时: Enfeeble\n> 秀肌肉时受到伤害: 吸收伤害转化为护甲,提高攻击伤害"
LANGUAGE.controls_crow                  = "> PRIMARY: Peck Sigils / Gibs \n> SECONDARY: Caw / Health Explosion"
LANGUAGE.controls_the_lost              = "> PRIMARY: 开火"
LANGUAGE.controls_spectral_revenant     = "> PRIMARY: Spectral 攻击\n> SECONDARY: 投掷nightmare精华\n> 攻击击中人类时: Nightmare and Tremor"
LANGUAGE.controls_fetid_maw             = "> PRIMARY: Poison 攻击\n> SECONDARY: 呕吐poison\n> RELOAD: 毒球轰炸"
LANGUAGE.controls_gonome                = "> PRIMARY: Burst Claws\n> ON HIT HUMAN: Poison\n> SECONDARY: Gut Throw\n ON GUT THROW HIT: Slow and Prey debuffs\n> RELOAD: Leap"
LANGUAGE.controls_harbinger             = "> PRIMARY: Burst 攻击\n> 击中人类时: Poison\n> SECONDARY: 投掷肉球\n 肉球击中人类时: Slow and Prey debuffs\n> RELOAD: 飞跃"
LANGUAGE.controls_breachprowler         = "> PRIMARY: Attack\n> SECONDARY: Shoot Breach Spikes"
LANGUAGE.controls_fleshfire             = "> PRIMARY: 炽热一击\n> SECONDARY: 投掷火球 \nRELOAD: 咆哮"
LANGUAGE.controls_dreadmammoth          = "> PRIMARY: Claw\n> SECONDARY: Leap\n> RELOAD: Moan> ON DEATH: Revive"
LANGUAGE.controls_hulk                  = "> PRIMARY: 攻击\n> SECONDARY: 独轮车泰山压顶\n> RELOAD: Enrage"
LANGUAGE.controls_dread_hulk            = "> PRIMARY: 攻击\n> SECONDARY: 独轮车泰山压顶\n> RELOAD: Enrage"
LANGUAGE.controls_cinder_thug           = "> PRIMARY: Fire 攻击\n> SECONDARY: 冲撞\n> SECONDARY WHILE CHARGING: 跃起,跃起过程中SECONDARY 下落撼地\n> 满充能冲撞击中人类: 燃烧爆炸\n> 击中防线时: 减少prop维修率\n> RELOAD: 上勾拳\n> ON 上勾拳击中人类: Burning Knockdown Punch"
LANGUAGE.controls_cinder_ghoul          = "> PRIMARY: Fire 攻击\n> SECONDARY: 投掷火球 \n> RELOAD: 嚎叫"
LANGUAGE.controls_tarmesh               = "> PRIMARY: Gunk Claws\n> SECONDARY: Puke Gunk\n> RELOAD: Tar Bomb"
LANGUAGE.controls_meteoric_eradicator   = "> PRIMARY: Fire 攻击\n> SECONDARY: 投掷火球\n> ON DEATH: Fire Puddle"
LANGUAGE.controls_pigeon                = "> PRIMARY: 拉屎"
LANGUAGE.controls_seagull               = "> PRIMARY: 抓取/放下道具"
LANGUAGE.controls_banished_warrior      = "> PRIMARY: Sword Swing\n> HOLD PRIMARY: Charged Sword Swing\n> SECONDARY: Dash\n> SECONDARY CONNECTION TO HUMAN: Aoe Enfeeble up to to targets\n> RELOAD: Random Buff\n> CHARGE ON BANISHED: Dark Power, Wretched Might, Speed and Shield"
LANGUAGE.controls_behemoth              = ""
LANGUAGE.controls_dread_monger          = ""
LANGUAGE.controls_amalgam               = ""
LANGUAGE.controls_moroi                 = ""
LANGUAGE.controls_elemental             = ""
LANGUAGE.controls_frostbite             = ""
LANGUAGE.controls_nuclear_terror        = ""
LANGUAGE.controls_poison_anomaly        = ""
LANGUAGE.controls_gonarch               = ""
LANGUAGE.controls_tickledecimator       = ""

--ZE
LANGUAGE.ZE_WEP_BUY             = "按下 F3 打开 ZE购买菜单"
LANGUAGE.ZE_AFTER_BUY           = "你购买了一个"
LANGUAGE.ZE_WEP_EXIST           = "你已经拥有此武器"
LANGUAGE.ZE_WEP_COOLDOWN        = "武器菜单正在冷却(%ss)"
LANGUAGE.ZE_NADE_EXIST          = "你已经拥有一个手雷了!"
LANGUAGE.ZE_NADE_COOLDOWN       = "你的手雷购买正在冷却 (%ss)"
LANGUAGE.ZE_NADE_STOCK          = "你还剩 %s 个手雷可供购买"
LANGUAGE.ZE_WEP_TITLE           = "按下键盘相应的键进行选择"
LANGUAGE.ZE_LEADER_TITLE        = "指挥菜单"

LANGUAGE.ZE_ITEM_DROP           = "Press %s to drop your item."
LANGUAGE.ZE_ITEM_DROP_BIND      = "Bind a key to +zoom to drop your item."
LANGUAGE.ZE_ITEM_USE            = "Press %s (on the green circle) to use your item."
LANGUAGE.ZE_ITEM_USE_BIND       = "Bind a key to +use to use your item."

-- The help file... Quite big! I wouldn't blame you if you didn't translate this part.
LANGUAGE.help_cat_introduction      = "Introduction" --"介绍"
LANGUAGE.help_cat_survival          = "Survival" --"生存"
LANGUAGE.help_cat_barricading       = "Barricading" --"盖防线"
LANGUAGE.help_cat_upgrades          = "Upgrades" --"升级"
LANGUAGE.help_cat_being_a_zombie    = "Being a Zombie" --"当个丧尸"
LANGUAGE.help_cont_introduction     = [[<p> Welcome to Zombie Survival, the (zombie) survival simulator. ZS allows you to fight zombie attacks, create barricades, and even be part of the undead horde.</p> --"欢迎来到Zombie Survival,这是个(丧尸)生存模拟游戏. ZS让你可以攻击丧尸,建造防线甚至于变成尸潮的一部分."

<p>There are two teams: the survivors and the zombies. The humans win if they survive every wave. Some levels have special objectives to be completed, which may be optional or required to win.
If a human is killed then they'll come back as a zombie, which makes it even more difficult for the remaining humans.</p>  --"总共有两个阵营：丧尸和人类. 人类的主要目的就是活下来至最后, 而有些地图则是会有特殊的目标需要完成, 这些目标也许是必须也可能是不必要的. 如果人类被击杀了, 他们会重生为丧尸, 这使得活着的人类难度大大提升.

<p>The goal for the zombies is to kill all of the humans, making them all zombies and causing everyone to lose the round.
Alternatively, a zombie can kill four humans to be redeemed. This allows them a second chance at survival and victory.
Remember, the only way to win a round is to be a human when the round ends. Zombies can't technically win the game; zombies can only make everyone else lose!</p> --"丧尸主要的目标是杀死全部人类,把人类全部杀死就算胜利. 可是,丧尸可以通过击杀指定数量的人类复活. 这让他们有第二次机会活下来并取得胜利. 温馨提醒: 只有人类有胜利, 丧尸存在的意义是让人类输掉."

<p>A certain amount of people are chosen (or volunteer) for being the starting zombies. This amount is displayed at the bottom of your screen before the round starts.</p> --"在每局游戏的开场, 会有一定数量的人类被选为丧尸（自愿者）.数量会在游戏开始前,显示在屏幕的正下方."

<p><b>Use the buttons up top to get help on more specific things.</b></p>

<p>Tips for this section:
<ul><li>If you leave the game as a human then you'll rejoin as a zombie.</li> --"如果你在还是人类的时候离开游戏,重新加入你将会转变为丧尸"
<li>After a certain amount of time has gone by, even new players will spawn as zombies.</li> -- "经过一段时间后,新加入的玩家将会作为僵尸出生"
"<li>Use TEAM CHAT when needed. The default key is U and allows you to speak to only your team.</li> -- "必要的时候请使用队内聊天,默认按U使用队内聊天"
</ul></p>
]]
LANGUAGE.help_cont_survival             = [[<p>Tips for this section:
<ul><li>Holding the ZOOM key (default: Z) allows you to move freely through barricades while walking extremely slow.</li> -- "按住“放大”键（默认：Z键）可以让你穿越防线,代价是移动的极其缓慢."
<li>If a human is directly killed by a zombie then they will rise again wherever they stand. Make sure you end their misery before they give you any.</li> -- "如果一个人类被僵尸咬死,他们下一次站起来就不再是人类了.请确保在它们对你发起进攻前之前结束他们的痛苦."
<li>You're only given a certain amount of Worth to play with so think carefully what you should get!</li> -- "你的Worth点数是有限的,请仔细考虑你的配装!"
<li>You can create, save, load, delete, and mark as default carts by pressing F2. This saves a ton of time which could be better spent setting up barricades or creating game plans.</li> -- "你可以按F2键来创建、保存、加载、删除和设置默认配装.这可以节省大量的时间,而节省下来的时间可以更好地用于建立防线或制定游戏策略."
<li>A spot that feels safe one moment may be a death trap with more or different types of zombies roaming around. Always allow extra space and a "Plan B" if things get ugly.</li> -- "因为各种不同类型的僵尸在周围游荡,此刻还算安全的防线可能瞬间就会变成死亡陷阱.如果事情变得不妙,一定要留出额外的空间并准备“B计划”."
<li>You're useless to your team if you're not doing anything to help. You're even more useless to yourself since you're not getting any points or bigger weapons!</li> -- "如果什么事情都不做,你就毫无用处.因为你没有得到任何分数也就得不到更强大的武器!"
<li>By holding your SPRINT key for about ten seconds while looking at deployed objects that you own, you can pack them up for later use.</li> -- "看着属于你的放置物并按下“冲刺”键约10秒钟,你可以把它们打包带走,以便以后使用."
<li>Turrets without owners (a blue light) can be claimed by pressing USE on them. Ownerless turrets will not scan for targets!</li> -- "无主的炮塔（发着蓝光的）可以通过按“使用”键来认领.无主的炮塔将不会扫描目标!"
<li>Props that aren't nailed to something don't make very good barricades unless they're really heavy.</li> -- "没有被钉子固定住的物体并不能作为有效防线使用,除非它们真的很重."
<li>With enough punishment, doors can be thrown off their hinges.</li> -- "对门造成一定的伤害,就可以把它们从铰链上拆下来."
<li>Most props will become red with more and more damage.</li> -- "大多数物体会随着受到伤害的增加而慢慢变红."
<li>Zombies can spawn on top of each other if no humans are around to witness it.</li> -- "如果周围没有人类,僵尸可以在彼此身上出生."
<li>Most melee weapons have a longer reach than zombie claws. Use this to your advantage if you insist on defending with a melee weapon.</li> -- ""
<li>Players on the same team do not damage or collide with each other and can freely shoot and swing through each other.</li> -- ""
<li>Make sure you use a barricade to your advantage and stay behind it a good distance away from the zombies. Guns have an infinite range, zombie claws do not.</li> -- ""
<li>Your team members aren't always right, don't be a sheep! Zombies like to kill sheep.</li> -- ""
<li>Zombies can see your health, even through walls. Make sure to fall back when hurt as zombies will most likely try to pick you off.</li> -- ""
<li>Don't hide, zombies can sense you through walls and in complete darkness.</li> -- ""
<li>The Horde Meter at the bottom of the screen indicates how much of a damage and knockback resistance you have. Huddle up with other zombies for a big resistance when taking down strongholds!</li> -- ""
<li>If you don't have enough zombies to take down a barricade, try hunting for new "team mates" elsewhere.</li> -- ""
<li>Don't shoot zombies in the green gas! Zombies in the green gas are invincible!</li> -- ""
<li>Zombies are resistant to damage in the chest and even more so in the legs. Make sure you're aiming for the head as some zombies have the ability to get up again if you don't!</li> -- ""
<li>Although zombies take less damage in the legs, shooting them there will slow them down for a short time, enough to allow you or a team member to escape.</li> -- ""
</ul></p>
]]
LANGUAGE.help_cont_barricading            = [[<p>Barricading is an extremely important part of survival. It may seem like the undead aren't a threat early on but eventually they'll be powerful enough to kill your entire team in a few seconds.</p> -- ""

<p>The only thing keeping the zombies out is a well-built and well-maintained barricade.</p> -- ""

<p>There are a couple of tools that give you the ability to set this up. The one most useful tool is the hammer and nails. This allows you to nail down props which then must have the nails destroyed in order for the zombies to get to you.
Position the prop you want to nail by pressing USE on it to pick it up. You can hold SPRINT while holding it to lock it in place. Then take your hammer and right click where you want the nail to go. It's a good idea to nail the prop to a sturdy object such as a wall instead of other props.
Remember, when a prop is nailed it will forward the damage it takes to the nails themselves. You can repair nails by hitting them with the hammer but eventually they'll become too damaged to repair anymore. You can hold SHIFT with the hammer out to get a view of every single nail deployed on your screen as well as the owner.
If you think a nail is in a bad place or you'd like to reposition a prop, you can remove nails by pointing at it and pressing RELOAD. Be warned, if you take a nail that doesn't belong to you then you will be given a point penalty.</p> -- ""

<p>One other tool is the 'Aegis' Barricade Kit. This quick-deploying tool allows you to place boards on any surface or deploy them between two walls. It doesn't even need props. To use it, you need to position a board in a spot that is legal. The ghost will turn from red to green to let you know.
Deploy a board by pressing PRIMARY ATTACK. Rotate the board by using SECONDARY ATTACK and RELOAD. It uses boards for ammunition so boards you have from the Board Pack work as extra ammunition! You can pack up boards you've deployed by pressing SPRINT while pointing at it.</p> -- ""

<p>Another tool worth noting is the Turret. This tosses bullets at any zombie that gets in the way of its laser. Its only downside is that it requires ammunition. You can refill ammunition by pressing USE on it. This will give you bonus points for helping the team.
To deploy the turret, position it in a way so that the ghost is green. It must be on a solid surface (no props!). Rotate the turret with SECONDARY ATTACK and RELOAD. If you mess up, you can always pack the turret back up by pressing SPRINT while pointing at it. Remember, the turret will only fire at zombies that cross its tracking beam.</p> -- ""

<p>Tips for this section:
<ul>
<li>Use bigger props for barricades. Usually the prop has room for more nails. In addition to that, it even acts as cover from projectiles.</li> -- ""
</ul></p>]]
LANGUAGE.help_cont_upgrades             = [[<p>Points are obtained through killing zombies, healing team mates, and building defenses.
You can then exchange points in the Points Shop at Arsenal Crates or Sigils.</p> -- ""

<p>Tips for this section:
<ul>
<li>Try planning ahead. Buy extra pistol ammunition in the Worth menu so you have plenty to spare once you get your first upgrade.</li> -- ""
<li>You get points based on how much damage you deal and type of zombie you dealt the damage to.</li> -- ""
<li>Worth and Points are separate. Make sure you spend all of your Worth!</li> -- ""
</ul></p>]]
LANGUAGE.help_cont_being_a_zombie         = [[<p>Tips for this section:
<ul>
<li>You have an unlimited amount of lives, the humans only have one each. Don't be afraid to attack, attack, attack!</li> -- ""
<li>The regular Zombie class has the ability of durability. The only way to kill you for sure is to get shot in the head or be killed by a melee weapon. You don't need your legs.</li> -- ""
<li>Zombies can spawn on any active nest built.</li> -- ""
<li>With enough practice, you can use props to slam them in to humans from a distance.</li> -- ""
<li>Destroy deployables such as turrets and Arsenal Crates to cripple the humans.</li> -- ""
<li>With enough punishment, doors can be thrown off their hinges.</li> -- ""
<li>Most props will become red with more and more damage.</li> -- ""
<li>The Wraith is completely invisible while standing still or at a distance.</li> -- ""
<li>The Fast Zombie's lunge attack damage scales by how long you're in the air. The more air time you get, the larger the damage. Use your claw attack when in close range!</li> -- ""
<li>In addition to being extremely tough, the Poison Zombie can rip out chunks of its own poison flesh and throw them at humans by pressing SECONDARY ATTACK.</li> -- ""
<li>Most zombie claws have two chances to hit their target. If you "hit" your target when you click your mouse button then you're guaranteed a hit as long as they remain in range.</li> -- ""
<li>The Poison Headcrab's spit projectile can dim vision humans if it hits them in the head.</li> -- ""
<li>Go for the humans with low health! Other zombies are also attracted to them so they should be the easiest targets.</li> -- ""
<li>The Horde Meter at the bottom of the screen indicates how much of a damage and knockback resistance you have. Huddle up with other zombies for a big resistance when taking down strongholds!</li> -- ""
<li>If you don't have enough zombies to take down a barricade, try hunting for new "team mates" elsewhere.</li> -- ""
<li>If an area is too dark, try pressing your FLASHLIGHT button to toggle night vision.</li> -- ""
</ul></p>
]]

-- Place any custom stuff below here...